### ISSUE TITLE
Add styling to tags

### ISSUE THREAD

**Issue by moattarwork** [mbenford/ngTagsInput#128]
It would be nice to allow colouring tags based on their internal condition. Passing a function to the directive to return tag extended style will be quit helpful.

**Comment by klaoha06** [comment]
+1

**Comment by ninrod** [comment]
+1. Belo trabalho Michael.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
