### ISSUE TITLE
Support for RequireJS

### ISSUE THREAD

**Issue by facka** [mbenford/ngTagsInput#190]
Add this at the first line:
(function(window, angular, undefined) {'use strict';

and at the end this:
})(window, window.angular);

So it knows angular variable when using requireJS

**Comment by ChrisAitken** [comment]
has there been any update to this ?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
