### ISSUE TITLE
Add a tag limit to the autocomplete input with a way to elide and display further tags

### ISSUE THREAD

**Issue by charl** [mbenford/ngTagsInput#225]
The current maxTags setting only allows you to control how many tags are entered.

What I am thinking of is a visual way to elide the list of tags in the autocomplete input when they reach a configured amount of tags/input width.

The autocomplete input will then need to provide some form of elided message (something like: ...12 more) that when clicked will expand the input to a scrollable version of the input listing all selected tags.

The _max-labels_ config parameter for [angular-multi-select](http://isteven.github.io/angular-multi-select/) is an example of what I'm thinking of:

> max-labels 
> Maximum number of items that will be displayed in the dropdown button. If not specified, will display all selected items. 
> Example: If we use the input-model $scope.inputList above, then
> max-labels="1" will display: "Bruce Wayne, ... (Total: 2)" on the button.
> max-labels="0" will display: "(Total: 2)" on the button.

**Comment by zardaloop** [comment]
Hi @mbenford ,
Just going back to what you have suggested here https://github.com/mbenford/ngTagsInput/issues/210#issuecomment-52431874

How can you write this directive for Angular 1.3 because it does work for 1.2 but not for 1.3. 

Many thanks.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
