### ISSUE TITLE
Provide some way to discriminate between tags added via suggestion list or manually entered into input

### ISSUE THREAD

**Issue by charl** [mbenford/ngTagsInput#244]
In my use case I have two different types of data that I manage via the tags-input.

Name + Surname goes into the suggestion list and users can manually add telephone numbers to the input.

In my case I'd like to validate the tags added manually (telephone numbers) differently from the ones in the suggestion list.

This feature would go hand-in-hand with being able to provide one's own validation in a _[before tag added](https://github.com/mbenford/ngTagsInput/issues/100)_ event.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
