### ISSUE TITLE
Touch devices cannot hide auto-complete

### ISSUE THREAD

**Issue by offsky** [mbenford/ngTagsInput#246]
When you have a mouse and you click outside of the tags-input it blurs the input and closes the auto-complete list.  On an iOS device this doesn't happen when you touch outside and there is no way to dismiss the autocomplete list, which could potentially be obscuring some useful part of the webpage.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
