### ISSUE TITLE
AutoComplete: Prefer autocomplete suggestions when " add-from-autocomplete-only" is set to "false"

### ISSUE THREAD

**Issue by luckysoni** [mbenford/ngTagsInput#255]
When  add-from-autocomplete-only="false" we are allowed to add our own tags which is great but for instance if a tag exists in the auto-complete source but instead of click on the tag i type it and hit the enter key - the tag will be added with this will not be the same object that was populated by the auto-complete plugin.. it will instead create a new item, which is probably not the desired functionality.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by luckysoni** [comment]
@mbenford Thank you for having a look at this. I am not sure if #136 is the same as this issue. Let me clarify:
Suppose i am fetching tags from a database. Each tag is an object like the following (for example):
```javascript
{
    id: 1,
    name: someTag
}
```
If i now type the full tag name in the input, i.e. someTag and hit the enter/return key, a new tag is added. This new tag is a plain string and not an object which it should be because it already existed in the fetched tag's array. Though we can check for duplicate entries in our database, but this can cause issues when we need to use the tag in frontend before sending it to the backend for storing it. Hope this makes sense.

**Comment by mbenford** [comment]
I've mentioned #136 because it's about automatically selecting the first autocomplete suggestion when a hotkey is pressed, and that should minimize the odds of a new tag being created instead of selecting existing ones. Please note that I said *minimize*. If you want to be 100% sure that all tags come from a predefined list, you'll need to set the `addFromAutocompleteOnly` option as true.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by luckysoni** [comment]
Yes, thanks.
