### ISSUE TITLE
Use items as strings if displayProperty is an empty string.

### ISSUE THREAD

**Issue by Arekusei** [mbenford/ngTagsInput#277]
Example
```html
  <tags-input ng-model="book.tags" display-property="">
    <auto-complete source="searchTags($query)"></auto-complete>
  </tags-input>
```
If searchTags($query) return strings and we select item, then get in book.tags `{text: "..."}`, but need `"..."`
PS Sorry for bad English.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by Arekusei** [comment]
It is not always convenient. The requirement for a specific structure of the model is not very good.
But currently the problem for me is not relevant.

**Comment by mbenford** [comment]
There will always be a requirement for some specific structure, and it will never be convenient for every one. In fact, the first version of ngTagsInput worked only with array of strings, but it quickly became clear that that was too restrictive. You can easily map an array of objects into an array of strings (as I showed above), but not the other way around.

Anyway, I'm closing this issue since you said it's not important to you right now.

**Comment by gclouds** [comment]
I thing, it is an importtant features. I also wasted whole day finding out the solution.
