### ISSUE TITLE
 allowed-tags-pattern with delimiter not working

### ISSUE THREAD

**Issue by RobertHeim** [mbenford/ngTagsInput#278]
Hi,

this seems to reject all tags:

```
<tags-input ng-model="tags" add-on-comma="true" allowed-tags-pattern="/^[\- a-z0-9]{3,30}$/i">
</tags-input>
```

but it should of course accept e.g. aBc
I think the string needs to be converted to a RegExp?

**Comment by RobertHeim** [comment]
any chances that silverprizes solution will be merged?

**Comment by RobertHeim** [comment]
bump, I really need this!

**Comment by ksgupta** [comment]
I am having the same issue.  Did you get a chance to merge this anytime?

**Comment by silverprize** [comment]
There is a `onTagAdding` option. It's alternate to `allowedTagsPattern` completely.
I suggest a example.
```
<tags-input on-tag-adding=onTagAdding($tag)></tags-input>
```
```
$scope.onTagAdding = function($tag) {
  return YOUR_REGEXP.test($tag[your property name]);
};
```

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
