### ISSUE TITLE
Request for tag edit on double click

### ISSUE THREAD

**Issue by melnikovkolya** [mbenford/ngTagsInput#282]
Similar to how a tag-like email address converts to an editable text on a double click.

**Comment by donghwicha** [comment]
is this implemented?

**Comment by akaNightmare** [comment]
+1

**Comment by hmontazeri** [comment]
+1

**Comment by nevedimko** [comment]
+1

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
