### ISSUE TITLE
CSS for highlightMatchedText should not define font-size.

### ISSUE THREAD

**Issue by jgehrcke** [mbenford/ngTagsInput#288]
With `highlightMatchedText` set to true, an `<em>` tag encloses the text part to be highlighted. That is great so far. In the current CSS selector (`tags-input .autocomplete .suggestion-item em`), however, the font properties are over-specified (`normal bold 16px "Helvetica Neue",Helvetica,Arial,sans-serif;`). Most of the properties should simply be inherited, otherwise it is overly complex to change the font in the suggestion list. For changing the size, this should only require 

```
tags-input .autocomplete .suggestion-item {
    font-size: 11px;
}
```

The above CSS change yields a mixture of font sizes in the suggestion list (because the `<em>`-wrapped text has its size set to `16px`). As a workaround, a little CSS hack is required to make the highlighted text "inherit" the font size again:

```
tags-input .autocomplete .suggestion-item em {
    font-size: 100%;
}
```

I suggest that `tags-input .autocomplete .suggestion-item em` does not get styled at all. `<em>` should yield the desired effect in all browsers, shouldn't it?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
