### ISSUE TITLE
Custom message when there's no autocomplete item to show

### ISSUE THREAD

**Issue by fcis2008** [mbenford/ngTagsInput#301]
How can I add custom message when the auto complete doesn't return any value? ex: "No results found"

**Comment by sprakashg** [comment]
is this feature available now??

**Comment by willianribeiro** [comment]
+1

**Comment by abojar** [comment]
+1

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
