### ISSUE TITLE
Allow duplicate entries with different case

### ISSUE THREAD

**Issue by mlim1972** [mbenford/ngTagsInput#313]
Add configuration to allow entering the same values in different cases.

**Comment by mbenford** [comment]
Sounds useful. I'll add this to the backlog.

**Comment by mlr7x9** [comment]
Would pull request #339 fix this?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by amithsharma** [comment]
was there any fix given for this issue?
