### ISSUE TITLE
Pasting in IE fails to work with add-on-paste

### ISSUE THREAD

**Issue by LoganBarnett** [mbenford/ngTagsInput#325]
0. Install a Windows OS of some kind that uses IE 10 or 11.
1. Use ng-tags-input with the option `add-on-paste="true"`.
2. In IE, paste the following into the input: `foo,bar,bazz`
3. Expected behavior is for `foo`, `bar`, and `bazz` to exist as individual tags. Outcome is `foo` is in the input, and there are no tags.

Additionally, this error appears in the console:
`TypeError: Unable to get property 'getData' of undefined or null reference`

**Comment by mbenford** [comment]
Thanks for reporting this issue. :+1: 

I use Sauce Labs to run all tests against IE10 and IE12, but since the test for that particular scenario mocks out the event, it won't ever break. :(

I think Angular should have taken care of that by abstracting away the paste event so we don't have to deal with browser differences like this one. Seems like a good PR to be sent to them. :)
