### ISSUE TITLE
Autocomplete : "Error: error:dupes Duplicate Key in Repeater" exception if two objects returned have the same label

### ISSUE THREAD

**Issue by nicolasblanco** [mbenford/ngTagsInput#336]
Hello,

When querying a large database, the autocomplete fails with "Error: error:dupes
Duplicate Key in Repeater" exception if two or more objects have the same displayProperty even if the objects are totally different otherwise.

This is because the track functions in the plugin are always mapped to the displayProperty only.

It could be nice to be able to map these track functions to another attribute, like "id" (if the records are fetched from a database like in my case).

Thanks!

:smile:

**Comment by gae123** [comment]
Run into the same issue and totally agree.

**Comment by oteichmann** [comment]
If this feature would be implemented... How should the user distinguish between the duplicate display values?

**Comment by nicolasblanco** [comment]
@oteichmann : I totally agree, the user would not be able to distinguish between duplicate display values.

But when querying large datasets you don't own or control, it seems better to display some duplicates than to display nothing because of a JavaScript exception...

**Comment by mbenford** [comment]
@nicolasblanco 
That's been requested before (a few times, to be honest). It's in the project backlog already.

@oteichmann 
Yes, that kind of UX problem might be introduced, but IMO it's up to the developer to deal with it. I mean, if one doesn't want duplicate items in the autocomplete list, simply filter out them before returning the collection to the directive.

**Comment by eranimo** [comment]
I'm getting this error even though I have no duplicates

**Comment by andreicristianpetcu** [comment]
Here is my workaround:
I have by own directive on top of ngTagsInput. I use it to select users (and other stuff). I usually use first name + " " + last name. But if I have multiple users named "John Doe" I change the algorithm instead of showing two "John Doe" it shows + email so "John Doe (john.doe@example.com)" and "John Doe (john.doe@awesomedomain.eu)" all the non-doubles I show as they are so if I have a "Jane Doe" but only one, I don't show the email for her. This way I always have unique items for the tag input.

**Comment by mbenford** [comment]
This has already been implemented in master. There is a new option `keyProperty` that solves that problem. The latest build is available [here](http://shrub.appspot.com/ng-tags-input).

Can this issue be closed?

**Comment by vcardins** [comment]
Any plans to update bower soon? Also I tried to grab from github using
bower update but I couldn't build.
Thank you very much!

**Comment by thegregthomp** [comment]
Is there any documentation on how to use this?

**Comment by mbenford** [comment]
@thegregthomp Not yet. But it's similar to the `displayProperty` option:

```html
<tags-input ng-model="tags" key-property="id" display-property"text"></tags-input>
```

Both `id` and `text`must be properties of each tag object.

**Comment by mbenford** [comment]
v2.3.0 is already published on all distribution channels and it contains the `keyProperty` option.

**Comment by nikhilvm1993** [comment]
is key-property implemented for <auto-complete>.
My case is i am allowing to select from autocomplete and user can add tags manually by typing text.
So i am not able to give key-property for <tags-input> because my autocomplete items will have key-property id but not having for text entered by user.there key-property is undefined always.So throwing ngRepeat dupes error.Any help ?

**Comment by steelx** [comment]
@mbenford thanks worked fine for me 👍 
`key-property="id" display-property"text">`

**Comment by bharatpatil** [comment]
How about if I copy and paste tags.
