### ISSUE TITLE
Change restrict to 'EA' on both directives

### ISSUE THREAD

**Issue by 43081j** [mbenford/ngTagsInput#344]
In the case that someone doesn't want a custom element, `restrict` should be set to `EA` instead of `E`. 

This would need a CSS change to base the selectors on a class OR a tag, rather than just a tag.

There's a few reasons someone may not want a custom element in their source, such as HTML validation or older browser versions possibly.

**Comment by mbenford** [comment]
ngTagsInput was designed to be a custom HTML element from the very beginning. If you need to use it as an attribute applied to another element, I suggest you simply grab either the source code or the final script files and change them accordingly.

**Comment by 43081j** [comment]
It'd make little difference in terms of code, whichever way it was used, hence the suggestion.

Nevermind if there's little use for it though.

**Comment by benyitzhaki** [comment]
+ 1
I'm also editing the directive's restriction to EA each time i'm performing an upgrade to the code.. therefore i would also recommend changing the default to EA

**Comment by ArdentZeal** [comment]
+1

**Comment by mbenford** [comment]
Sorry for not replying sooner.

Unfortunately it's not so simple. I would have to write tests to ensure the directive would work as an attribute, and change the docs so people would know there's another way to use the directive. And there's the main point that I mentioned above: ngTagsInput was *designed* to be used as a custom element, so one could semantically express she/he is using an input with tagging capabilities.

Anyway, I'll let this thread open for a while to measure how often this is requested.

@benyitzhaki I suggest that you fork this repository, change the code accordingly and then rebase your branch on top of the master branch when you want to update it to the latest version. That way you won't need to keep changing it manually every time a new version is released.

**Comment by 43081j** [comment]
It may well have been designed as a custom element, but that's little reason to implement new functionality.

Only a couple of simple tests need adding and it'd take a single line in the README specifying it can be used. Considering you already have a PR with the code changes, it won't take much effort as you just need to throw up a test to compile the attribute-based tag and check that it worked correctly.

Generally, it isn't a great design decision to restrict use of a directive to being an element, especially when there exists no reason to do so (functionally, it makes no difference at all).

**Comment by mbenford** [comment]
> It may well have been designed as a custom element, but that's little reason to implement new functionality.

No, it's not. That design decision means that I care more about markup that makes semantic sense than markup that is simply "valid". And as a direct consequence of that, browsers that don't support custom elements aren't targeted by this project (in practice, that means IE 8/9).

But, as I said, let's keep this thread around for a while so we can see whether this is a critical issue or not. In the meantime, I wonder if you could take a look at the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file and adjust your PR accordingly?

**Comment by 43081j** [comment]
It's more to do with consistency than browser support, really. Some people prefer custom elements, some prefer attributes, this is one reason why angular supports both. It should be the choice of the user such that the code produced by this is consistent with the rest of their project.

As for reading the contributing file, the only thing I really missed is the additional test, if that's what you're referring to. Anyhow, no time right now, maybe you could have a go at writing the couple-of-lines test needed for this?

**Comment by mbenford** [comment]
I don't think that's the main reason Angular supports both elements and attributes directives. From their [Guide on directives](https://docs.angularjs.org/guide/directive):

> **When should I use an attribute versus an element?** Use an element when you are creating a component that is in control of the template. The common case for this is when you are creating a Domain-Specific Language for parts of your template. Use an attribute when you are decorating an existing element with new functionality.
>
> Using an element for the myCustomer directive is clearly the right choice because you're not decorating an element with some "customer" behavior; you're defining the core behavior of the element as a customer component.

That aligns pretty well with ngTagsInput, in addition to being semantic meaningful. That will become even more evident in Angular 2.0, where there will be different annotations for creating custom elements and attributes directives (Angular 2.0 calls them *component directives* and *decorator directives*, respectively). I honestly don't know if it'll be possible to have a directive that's both a component and a decorator. If I had to guess, I'd say it won't.

**Comment by 43081j** [comment]
That would be why I said "one reason why", I am aware of their guide.

You pretty much need to add a single test and a couple of lines to your readme to satisfy a request made by at least 3 people. Not everyone wants to use a custom element, for various reasons, it shouldn't really matter to you why, especially since the change to support it is so small.

**Comment by beradrian** [comment]
+1

**Comment by Bessonov** [comment]
Actually, we must support ie8+ and therefore we use all directives as attributes with 'data-' prefix. ngTagsInput is only one directive, which doesn't support 'A'-mode. It works with createElement-Hack, but it's inconsistent with all other directives.

And therefore +1 to this issue.

BTW, because ngTagsInput supports only angular before 1.3, it make sense to support ie8/9. ie8 is only one reason to stick with angular 1.2.x (angular 1.3 drop support for ie8). It's would be nice to add lines like:

    if ($sniffer.msie && $sniffer.msie <= 8) {
        document.createElement('tags-input');
        document.createElement('auto-complete');
    }

to ngTagsInput.

Additionally, I would prefer clean cut (branches) between supporting angular 1.2 and current version because of ie8 support, which is very important for enterprise customers.

BTW, great work!

**Comment by mbenford** [comment]
@Bessonov 
> Actually, we must support ie8+ and therefore we use all directives as attributes with 'data-' prefix. ngTagsInput is only one directive, which doesn't support 'A'-mode. It works with createElement-Hack, but it's inconsistent with all other directives.

> And therefore +1 to this issue.

Enabling the directive to work as an attribute is totally different than making it work with IE 8/9. Supporting those versions was never a concern and therefore several parts of the code may be incompatible with them.

> BTW, because ngTagsInput supports only angular before 1.3, it make sense to support ie8/9.

I don't think I agree with that. Each library can have their own requirements and they don't have to be the same as Angular's.

> Additionally, I would prefer clean cut (branches) between supporting angular 1.2 and current version because of ie8 support, which is very important for enterprise customers.

I'm not sure yet about that will be handled. I'm not fond of having two different versions published at the once because it's twice the amount of work to maintain them. Trust me. It's already hard with a single one. And again, ngTagsInput doesn't support IE 8 (and 9, for that matter). If it happens to work, it's purely by chance.

> BTW, great work!

Thanks man! :)

**Comment by Bessonov** [comment]
> I don't think I agree with that. Each library can have their own requirements and they don't have to be the same as Angular's.

Ok, I create a fork [ngTagsInput.ie8](https://github.com/Bessonov/ngTagsInput.ie8) for fighting ie8 issues.

**Comment by mbenford** [comment]
@Bessonov That's great! I was going to add a link to your fork to the README file, but then I saw your disclaimer. Are you planning to delete your fork once you're finished with it?

**Comment by Bessonov** [comment]
No, I don't planning to delete my fork and I will accept pull-requests etc. With throw-away I mean there is neither official support for nor I have requirement to have new tests, coverage, documentation and so on. ie8/9 isn't worth it :o) I changed my header to reflect this.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
