### ISSUE TITLE
last tag lost in race between blur and click

### ISSUE THREAD

**Issue by amc1804** [mbenford/ngTagsInput#347]
Suppose the user types "foo" into a tags-input, then clicks on a button,
which triggers a blur event on the tags-input and a click event on the
button.  The blur event causes a "foo" tag to be added to the model, and
let's say the click event calls some function that looks at the model.
Although the browser orders the blur event before the click event, the
use of $timeout in the blur handler allows the tag creation to happen
after the click handler has already looked at the model.

Of course, the user's intention is almost certainly to have the button
take some action that depends on the text just typed.

Any suggestions?

Does the blur handler really need to use $timeout?

Thanks,
AMC

**Comment by mbenford** [comment]
Sorry for not replying sooner.

Nice catch. I understand the problem but I don't know how to fix it right now. I'll add this to the backlog so I can work on it later. 

The timeout in the `blur` handler is needed in order to correctly determine what element is active right after the directive had lost focus. Without that minimum delay, `document.activeElement` returns the `body` element.

**Comment by B1aZer** [comment]
We can fix this issue with something like this:

```
                .on('blur', function() {
                    if (!lostFocusToChildElement) {
                      scope.hasFocus = false;
                      events.trigger('input-blur');
                    }
                });

            element.on('mouseenter', function(e) {
              lostFocusToChildElement = true;
            });

            element.on('mouseleave', function(e) {
              lostFocusToChildElement = false;
            });
```

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
