### ISSUE TITLE
<auto-complete> doesn't work

### ISSUE THREAD

**Issue by bonbon1702** [mbenford/ngTagsInput#348]
tags-input work fine for me but when i include auto-complete it break:
in my html
```
<tags-input ng-model="tags">
                <auto-complete source="loadItems($query)"></auto-complete>
            </tags-input>
```
in my controller
```
scope.tags = [
            { text: 'Tag1' },
            { text: 'Tag2' },
            { text: 'Tag3' }
        ];

        $scope.loadTags = function(query) {
            return $http.get('tags.json');
        };
```

when i type, i log error 
```
TypeError: Cannot read property 'then' of undefined
    at ng-tags-input.min.js:1
    at angular.js:14261
    at completeOutstandingRequest (angular.js:4387)
    at angular.js:4688
```

**Comment by bradeaton** [comment]
Shouldn't your scope.tags be like this?

`scope.tags = [
            { 'text': 'Tag1' },
            { 'text': 'Tag2' },
            { 'text': 'Tag3' }
        ];`

**Comment by scottbcovert** [comment]
Looks like you're binding the source attribute to a function named 'loadItems' but then defining 'loadTags' in your controller

**Comment by mbenford** [comment]
Sorry for not replying sooner.

It seems that @scottbcovert has nailed it. Questions like this one should be posted on StackOverflow since it would be visible to many people and the odds to get a quick response are much better. 

I'm closing this issue, but you can reopen it at will if you need more information.
