### ISSUE TITLE
Disable remove option  ?

### ISSUE THREAD

**Issue by rawoke083** [mbenford/ngTagsInput#358]
HI is there a way to disable removal of tags (via button and key) ?
PS. Nice project :)

**Comment by quzma** [comment]
+1

**Comment by mbenford** [comment]
Sorry for not replying sooner.

Currently there's no such feature available. I fail to see how that would be useful, though. I mean, how would the user remove a tag added by mistake? It's like having an input element with the backspace key disabled; you would have to perfectly enter the text because you wouldn't be able to correct any mistake.

**Comment by quzma** [comment]
For me use case was to remove backspace binding since it has other used in the app.

**Comment by mbenford** [comment]
@rawoke083  v2.3.0 will introduce a new callback called `onTagRemoving` that can be used to prevent a tag from being removed. So I think you'll be able to achieve what you want.

Can this issue be closed?

**Comment by rawoke083** [comment]
Yup !

**Comment by sibeliusseraphini** [comment]
I have an use case for this:

![breadcumb](https://cloud.githubusercontent.com/assets/2005841/12493011/40248fb8-c06a-11e5-9c99-30278d913871.png)

Image if I want to create a hierarchical structure based on the previous tags, like Brazil / São Paulo / São Carlos - to select a region.

I would like to disable, hide or remove the remove button, so the user should only return the last tag added
