### ISSUE TITLE
Correcting loadOnFocus issue...

### ISSUE THREAD

**Issue by Herisson-88** [mbenford/ngTagsInput#377]
line 598

if (options.loadOnFocus || shouldLoadSuggestions(value)) {
                        suggestionList.load(value, tagsInput.getTags());
                    }

and not

if (options.loadOnFocus && shouldLoadSuggestions(value)) {
                        suggestionList.load(value, tagsInput.getTags());
                    }

**Comment by mbenford** [comment]
That line is correct. Upon focus, the autocomplete list is displayed if the `loadOnFocus` option is true **and** all other rules apply.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by Herisson-88** [comment]
for empty field loadOnFocus won't load, on my point of view that was an
issue. In fact I use another select because this one to buggy...

2015-03-14 18:43 GMT+01:00 Michael Benford <notifications@github.com>:

**Comment by mbenford** [comment]
If you want the autocomplete list to load when the input is/gets empty you need to set the `loadOnEmpty` option to true. I would have said that before if you had explained your problem instead of assuming there was a bug in the code. 

Anyway, it's great that you have found another component that better suits your needs. Happy for you, man.
