### ISSUE TITLE
How to add class to tag input element based on the object values of current tag

### ISSUE THREAD

**Issue by mikethejet** [mbenford/ngTagsInput#391]
Hi, can I ask is there a way to add class -  to one tag input ement, that is based on the object values of current tag.
*_For example: *_ I want different color from value of each tag based on style object property.
Properities:

``` php
[0] => 
array(
  ['idTag'] => 1
  ['stick'] => 'dog'
  ['style'] => 'blue'
  )

[1] =>
array(
  ['idTag'] => 3
  ['stick'] => 'whistle'
  ['style'] => 'red'

[2] =>
array(
['idTag'] => 2
['stick'] => 'horse'
['style'] => 'blue'


```

Is there any way ?

**Comment by pedrogusman** [comment]
+1

**Comment by mbenford** [comment]
Sorry for not replying sooner.

This is already in the project backlog. Take a look at #273.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by mikethejet** [comment]
Backlog ok yes closed : ) thank you so much

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
