### ISSUE TITLE
Removing items from tags input, not shown in autocomplete list if already opened

### ISSUE THREAD

**Issue by Hubrus** [mbenford/ngTagsInput#410]
Hi,

If you set minLength to 0 and loadOnDownArray, loadOnEmpty and loadOnFocus on true for autocomplete, when removing one item from input and the autocomplete list is opened, the deleted item will not appear in autocomplete, till a search is made.

Plunker: http://plnkr.co/edit/zp5TMt?p=preview
Video: http://screencast.com/t/Kzx5xwCFYJ

Thanks!

**Comment by mbenford** [comment]
I'm aware of that. I thought it wouldn't be an issue because the user wouldn't be interested in adding a tag she/he had just removed.

Do you expect the autocomplete list to be reloaded after a tag is removed?

**Comment by mbenford** [comment]
There's no way to do that right now. I'll add this to the backlog so I can fix it later.

**Comment by paulflo150** [comment]
You could always just bind to on-tag-removed and refresh it yourself when an element gets removed.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
