### ISSUE TITLE
autocomplete directive load data slowly when user input data quickly

### ISSUE THREAD

**Issue by HeavenGoGo** [mbenford/ngTagsInput#418]
Recently I use tag input directive to implement one task. There are more than 4000 records to load in the autocomplete list. As we know, when we type character and it fire the "input-changed" event to load data,  so if user type character quickly, it will become very slow even pause when load data to display.

I also find that the data process will not cost much more time. the reason is that the user input data quickly and the "debounce-delay" is 200, so it will execute the load function frequently, because the amount is 4000, it will also cost much time to present in page. i know there is a property called "max-results-to-show", but I should load all data one time.

With this situation, it will cause that stop the user typing words, and the drop down list also no response to user. i think it is load data asynchronously, but in fact it is not, especially in IE 11, it just a disaster.

How to process this problem?

**Comment by mbenford** [comment]
I suggest that you don't load all data at once, for two reasons:

1) There's a [limit](http://stackoverflow.com/questions/9682092/databinding-in-angularjs) on how many bindings Angular can handle at every digest cycle before everything gets too slow. 4000 is way above that limit.
2) I fail to see how displaying 4000 elements at once is useful to the user. She won't navigate through all that items in order to find what she is looking for. You should use the text she types to provide the best results possible. Imagine how bad it would be if Google displayed 4000 results at once.

You may try to create [a custom template](http://mbenford.github.io/ngTagsInput/documentation/guides/custom-templates) and use some `bind-once` directive in order to prevent too many bindings from being created, but I honestly don't think you should display so many items at a time.

**Comment by HeavenGoGo** [comment]
thanks for your advice.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by hellsan631** [comment]
Just to give a possible solution. I preload all of my tags into an object in the scope. I set the autocomplete to a filter of that list of objects.

Here is a plunker of what's done:

http://plnkr.co/edit/bx7F0QKTJLZ6fHztOuzI

**Comment by mryellow** [comment]
> the "debounce-delay" is 200, so it will execute the load function frequently, because the amount is 4000,

I believe this is a bug. The debounce delay should be holding off requests regardless of how long your response takes. Your long running request should be throttled like any other. 

1 request should be sent and then waited for.

As your request is longer than the debounce delay it ends up triggering multiple times while waiting for the response. That should not happen.
