### ISSUE TITLE
Set $touched state added in Angular 1.3

### ISSUE THREAD

**Issue by ValentinH** [mbenford/ngTagsInput#419]
I have noticed your very cool commit to support Angular 1.3 (3355f3fa74). However, Angular 1.3 brought a $touched concept to check if a field has already been focused/touched. In order to follow this concept, this line needs to be added in the [`input-blur` block](https://github.com/mbenford/ngTagsInput/blob/master/src/tags-input.js#L364):

``` js
ngModelCtrl.$setTouched();
```

[Here's](https://docs.angularjs.org/api/ng/type/ngModel.NgModelController) the $setTouched doc.

What do you think?

**Comment by mbenford** [comment]
I'm definitely going to use that. That commit you've mentioned was just about making the current source code compatible with Angular 1.3. From now on I intend to use all new features that makes sense to this project.

Thanks for the tip! :+1:

**Comment by cdroulers** [comment]
I actually get $touched == true when cliking in the field, but $pristine is always true, no matter what I do!

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
