### ISSUE TITLE
key-property is not working

### ISSUE THREAD

**Issue by hopewise** [mbenford/ngTagsInput#422]
Hello,

I've tried to set key-property to 'title' instead of default value 'text' but, it didn't work, it only accepts 'text' key..

Thanks for great work!

**Comment by mbenford** [comment]
Could you provide a Plunker showing your problem? You can use [this template](http://plnkr.co/edit/tpl:Y7cuEGojnyGLbsUXJL1k).

**Comment by mbenford** [comment]
Any update on this?

**Comment by Amerr** [comment]
```
my Taglist =[ { id: 1, tag: { name: 'tag1' } },  { id: 2, tag: { name: 'tag2' } } ]
```
How to specify the key-property to " tag.name"
<tags-input ng-model="part.productTagging" key-property="$tag.name">. is This correct ?

**Comment by jinwyp** [comment]
still not working now ,  I want to  change  'text' field to 'name' when bingto ngModel data .

**Comment by mbenford** [comment]
@hopewise Any update on this issue?

@Amerr Shouldn't you use the `id` property as the tag identifier instead of `tag.name`?

@jinwyp Sure. Take a look at [this plunker](http://plnkr.co/edit/QYfjyVYhyLDniOANbRmY?p=preview). It uses Angular 1.2.28 because currently ngTagsInput doesn't support v1.3.

**Comment by jabbadubba** [comment]
The example of the plunker works with static data because you explicitly defined the id property on the objects, but still you can't add duplicate values because new objects are created without that id property. You can only add one "Tag1" tag before it fails. Actually it fails even if you don't enter duplicate values (i.e: "Tag2") because of the lack of the id property. Am I missing something?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by CristiGuran** [comment]
Hi, was this ever solved? I don't have a way to add ids dinamically and I get "[ngRepeat:dupes] Duplicates in a repeater are not allowed." error when saving the data.

Thanks and regards,
Cristi
