### ISSUE TITLE
ng-model not binding

### ISSUE THREAD

**Issue by firecentaur** [mbenford/ngTagsInput#426]
Hi there, I am using ng-tags to select users from the system,
I bind using ng-model="usersInvited"

but when my controller examines "scope.usersInvited" it is undefined

**Comment by firecentaur** [comment]
I fixed this by explicitly defining scope.usersInvited =[]; now it works

**Comment by mbenford** [comment]
What version of ngTagsInput are you using? And could you post your markup?

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by sravankumaroneness** [comment]
I am getting the above problem only in mozilla firefox latest version. Like from the drop-down once i Selected any of the Item, The ng-model is not updating and also 
"  self.add = function(tag) { } ", in this function the tag is coming as a empty string only in firefox.

Please help me to resolve this issue

**Comment by BaurzhanSakhariev** [comment]
Information for directive users: 

I also had such problem but the reason was in ```ng-if ``` in ```tag-input```. I used primitive type in ```ng-if``` and it created own child scope and put ng-model th that scope. Use ng-show or use object in ng-if.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
