### ISSUE TITLE
Autocomplete copies objects when selecting tag

### ISSUE THREAD

**Issue by jinder** [mbenford/ngTagsInput#430]
Hi,

I was trying to do some === comparisons with the objects that represent tags added via the autocomplete option, and was puzzled when they didn't work.  I tracked it down to the fact that they're copied using angular.copy in the addSuggestions function:

```
                if (suggestionList.selected) {
                    tagsInput.addTag(angular.copy(suggestionList.selected));
```

Is there a reason why they need to be copied?  Would it be possible to change this or add an option to change the behaviour? (Happy to submit PR)

Thanks!

**Comment by mbenford** [comment]
The autocomplete suggestion is copied so it can be later changed without affecting the autocomplete list. For instance, if the `replace-spaces-with-dashes` option is on and the user selects a suggestion containing spaces, ngTagsInput will replace those spaces with dashes, thus changing the original object and messing with the autocomplete list.

I suggest that you do your comparison by using some unique property instead of the objects themselves. If that's not possible, then I guess the way to go is to fork the main repo and change the aforementioned line yourself.

Let me know if I can help you with anything else.

**Comment by jinder** [comment]
Okay - thanks for the explanation!  We're already comparing by a key field, so we will carry on doing that.
