### ISSUE TITLE
W3C validation

### ISSUE THREAD

**Issue by beradrian** [mbenford/ngTagsInput#432]
Because `tags-input` directive (`auto-complete` too) is limited to the elements, W3C validator will fail.
If these won't be limited to elements, you could actually to `<div data-tags-input>` which will validate.

**Comment by mbenford** [comment]
Both directives were designed to be used as custom elements. But if you don't want to use them that way, you can simply fork the main repo and change the `restrict` option to either `EA` or `A` [here](https://github.com/mbenford/ngTagsInput/blob/master/src/tags-input.js#L149) and [here](https://github.com/mbenford/ngTagsInput/blob/master/src/auto-complete.js#L133).

**Comment by beradrian** [comment]
Why not consider making this as part of the main repo? Are there any drawbacks?

**Comment by mbenford** [comment]
No technical drawbacks; just more code for me to maintain that I'm not sure most people will use. This has been discussed [before](https://github.com/mbenford/ngTagsInput/issues/344), and I stand by my position that semantic markup is more important that markup that pass some validation. For instance, compare the following snippets:

````html
<tags-input ng-model="tags">
    <auto-complete source="loadTags($query)"></auto-complete>
</tags-input>
````

````html
<div data-tags-input data-ng-model="tags">
    <div data-auto-complete data-source="loadTags($query)"></div>
</div>
````

The second snippet is so convoluted to me that it almost makes no sense. It conveys no meaning - what two `div`s have to do with a tags input and its autocomplete?

Besides, validations like W3C will probably become meaningless when web components become a reality - some could say that they are already a reality, since tools like Angular enable us to use them today.

That all being said, I have no intention in making anyone's life harder. If a significant number of people want that "feature", I'll indeed implement it. Drop by the [other issue](https://github.com/mbenford/ngTagsInput/issues/344) and leave your "+1". :)
