### ISSUE TITLE
placeholder='' not working

### ISSUE THREAD

**Issue by Jakobovski** [mbenford/ngTagsInput#433]
Hi,

I noticed issue #86. I would like to be able to set the placeholder to an empty string on the directive properties themselves and not in the app configuration.  Is there a way to do this that I am unaware of? If not I am happy to make the code contribution.

Thanks

**Comment by mbenford** [comment]
Most options have default values, so when you don't provide `placeholder` with a value, it defaults to some predefined one. That's why you need to change the default value to an empty string and that can only be done by using the `tagsInputConfigProvider` within the application's `config` function.

Technically that's just a side effect of how Javascript handles falsy values (`''`, `false`, `0`, `undefined` and `null` are all the same to Javascript). There's actually no code explicitly prohibiting an empty placeholder.

If you want to send a PR, all you have to do is provide a validator to the `placeholder` option. Take a look at the `type` attribute. It uses a validator.

**Comment by itanex** [comment]
Is there any movement on this? I have tried to use the following process:

`<tags-input placeholder="{{placeholdertext}}" on-tags-added="tagAdded()"></tags-input>`

and then in my JS

```javascript
    scope.placeholdertext = 'my placeholder text';
    scope.tagsAdded = function() {
        scope.placeholdertext = "    ";
    }
```

However, this doesn't seem to get the job done as its not re-evaluating the markup. Tips??

**Comment by kotmatpockuh** [comment]
@mbenford  any ideas with @itanex issue?

**Comment by itanex** [comment]
I never had success with this.

**Comment by kotmatpockuh** [comment]
@itanex i done it so: https://github.com/mbenford/ngTagsInput/issues/479

**Comment by evillemez** [comment]
I did this by escaping a unicode non-breaking space:

```
$scope.placeholderText = "\u00A0";
```

This doesn't address the issue of changing the placeholder dynamically, just the empty space.

**Comment by sibeliusseraphini** [comment]
I think we should be able to change the placeholder dynamically as well

**Comment by mbenford** [comment]
Sorry for the very late reply.

Most options can be dynamically changed, including the placeholder, and that has been so for [quite some time](https://github.com/mbenford/ngTagsInput/issues/73). But it's not the default behavior, for performance reasons, and one needs to tell ngTagsInput what options should behave that way. More information on how to do that can be found [on the docs](http://mbenford.github.io/ngTagsInput/documentation/global-configuration).

**Comment by sibeliusseraphini** [comment]
This code solve this:

```
function(tagsInputConfigProvider) {
      tagsInputConfigProvider.setActiveInterpolation('tagsInput', { placeholder: true });
    }
```

**Comment by bulv1ne** [comment]
Didn't work for my, only way I could clear the placeholder was with:

```js
.config(function(tagsInputConfigProvider) {
    tagsInputConfigProvider.setDefaults('tagsInput', { placeholder: '' });
});
```

@sibeliusseraphini solution didn't work for me

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
