### ISSUE TITLE
Spinner icon request

### ISSUE THREAD

**Issue by Jakobovski** [mbenford/ngTagsInput#434]
Hi,

I would like an option to display a spinner icon while waiting for results from an async service. If this is something you are interested in I am happy to contribute the functionality to the project.

**Comment by mbenford** [comment]
This indeed seems like a nice feature.

Would you mind taking a look at the existing issues? I think this has been requested before. If it hasn't I'll add this issue to the backlog.

**Comment by yhourdel** [comment]
Hi,

I've given an example in #514

**Comment by shyamal890** [comment]
+1

**Comment by gwenael-louandre** [comment]
Hi,

Can you tell me if something has been done about this point or if this is forecast? I need this kind of feature because I request a very large Active Directory so I have to wait 4-5 seconds to have the result. The best behaviour would be to show the beginning of the list with the spinner each time there is a modification in the tag.

Thank you

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by shlomisas** [comment]
we need this feature please!

**Comment by amigup** [comment]
Hello @mbenford - Can you please a have look for this feature.  I need this feature to show spinner as the data is being loaded from remote server which takes 2-3 seconds. so during search, there is no user experience about what's happening in the background. Can you please plan for this feature?
