### ISSUE TITLE
Allow Multiple iterations on a single page.

### ISSUE THREAD

**Issue by wandertosee** [mbenford/ngTagsInput#438]
I created a solution for this, should I post for a pull request?

**Comment by mbenford** [comment]
I'm sorry. I have no idea what "multiple iterations on a single page" means. :\

**Comment by wandertosee** [comment]
When I have multiple inputs using ngtagsinput angular throws an error.

Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: {0}, Duplicate key: {1}, Duplicate value: {2}

**Comment by mbenford** [comment]
Could you provide a plunker showing your problem? You can use [this template](http://plnkr.co/edit/tpl:Y7cuEGojnyGLbsUXJL1k).

**Comment by pluschnikow** [comment]
I have the same Error: "[ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: tag in tagList.items track by track(tag), Duplicate key: translation.requested" ... the solution is to use "track by $index"

**Comment by mikelynn2** [comment]
i get this same error as well.  Its only when you're using the autocomplete on the 2nd one.  @wandertosee can you post the pull request?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
