### ISSUE TITLE
Not sure if this is an issue: autocomplete bug in min.js version?

### ISSUE THREAD

**Issue by michahell** [mbenford/ngTagsInput#439]
Hi,

Great ng-component, I love how feature rich it is and how easily customizable! (I'd like to tip you, but gratipay is for sustainable tipping, not one-off tips unfortunately. Flattr does one-offs I think, if you'd create a Flattr account i'd Flattr you!)

I might have found a bug: 
When I use the min.js version, my autocomplete function throws an error:
http://s23.postimg.org/5so4bowe3/Screen_Shot_2015_04_26_at_01_39_52.png

while if I use the non-minimized version it 'just works':
http://s21.postimg.org/pdu9cspkn/Screen_Shot_2015_04_26_at_01_40_54.png

I don't mind using the regular version, so low priority :)
The version I use is the latest, ng-tags-input#2.3.0

**Comment by mbenford** [comment]
That's really odd. What version exactly of Angular are you using?

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by michahell** [comment]
Not sure, will test later tonight! sorry for delay in answering, haven't been actively working on this project.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
