### ISSUE TITLE
bower.json "Main" - Should not be minified files

### ISSUE THREAD

**Issue by markwpearce** [mbenford/ngTagsInput#441]
According to the bower spec, the "main" key in bower.json (which lists the main files in the package) should have the unminified files, yet ng-tags-input lists the minified files.

https://github.com/bower/bower.json-spec#main

(I'll try to submit a pull request if I can figure out how you're building your bower.json file)

**Comment by mbenford** [comment]
Sorry for not replying sooner.

Thanks for pointing that out. I'll try to fix it for the next release.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
