### ISSUE TITLE
Start typing, than delete with long press of "backspace" key leaves autocomplete opened

### ISSUE THREAD

**Issue by hazzik** [mbenford/ngTagsInput#443]
1. Start typing something long to display autocomplete until the autocomplete is display
2. Press backspace and hold until everything removed
3. The autocomplete will be closed and then reopened

I've reproduced this on http://mbenford.github.io/ngTagsInput/demos ([Simple tags input with autocomplete](http://embed.plnkr.co/bDx54d/preview))

![image](https://cloud.githubusercontent.com/assets/144791/7488353/30d31b7a-f41d-11e4-882b-1e46bcf21484.png)

**Comment by mbenford** [comment]
Sorry for not replying sooner.

I think this was "accidentally" fixed in the latest release. I wonder if you could test it again?

**Comment by mbenford** [comment]
Any updates on this issue?

**Comment by hazzik** [comment]
I think can be closed

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
