### ISSUE TITLE
List of values instead of list of objects?

### ISSUE THREAD

**Issue by im1dermike** [mbenford/ngTagsInput#448]
I didn't see this anywhere in the documentation, but, by default, the model is like this:

```
 [{"text":"Tag1"},{"text":"Tag2"},{"text":"Tag3"}]
```

I understand that you can change the name of the key (in the key-value pair), but is there any way to have the model be a simple list of strings?  Eg:

```
 ["Tag1","Tag2","Tag3"]
```

FWIW, other tag input libraries allow for this and, in my case, this is the model I need to send to the server.

**Comment by IagoLast** [comment]
+1

**Comment by rehand** [comment]
I need the same behaviour. It would be nice to enable this by simply setting 'key-property' to null or "".

**Comment by mbenford** [comment]
Sorry for not replying sooner.

That's not currently possible, but there is [an issue](https://github.com/mbenford/ngTagsInput/issues/437) for it on the backlog already. It'll probably be implemented in the next release.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
