### ISSUE TITLE
Turkish character problem of Autocomplete

### ISSUE THREAD

**Issue by mparlak** [mbenford/ngTagsInput#449]
Turkish character problem in IE 9, let me live.as the name "Kasım" the written word doesn't result but when comes the results of writing "Kasim". ' ı ' as ' ' taking this character.
(ç,ş,i,ü,ö,ğ)

**Comment by mparlak** [comment]
I solved this problem :)  Under the 'tagsInput' directive->scope.eventHandlers-> under the change function.I used that toUpperCase() function.

before:
events.trigger('input-change', text);

after:
events.trigger('input-change', text.toUpperCase());

**Comment by mbenford** [comment]
Sorry for not replying sooner.

Could you provide a plunker showing your problem? You can use [this template](plnkr.co/edit/tpl:Y7cuEGojnyGLbsUXJL1k).

Also, does it happen only in IE9? ngTagsInput supports only IE10+

**Comment by mbenford** [comment]
Any update on this?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
