### ISSUE TITLE
Suggest List Dismiss

### ISSUE THREAD

**Issue by flik930** [mbenford/ngTagsInput#454]
I am wondering if I click somewhere else outside the suggest list, I can dismiss it.

**Comment by mbenford** [comment]
Sorry for not replying sooner.

Yes, that's the default behavior.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
