### ISSUE TITLE
Support for array of objects as a list of tags

### ISSUE THREAD

**Issue by mbenford** [mbenford/ngTagsInput#46]
Currently the directive only supports arrays of strings as a list of tags. Although that probably covers most use cases, it could also support an array of objects so applications that have a list like this

```
[
    { id: 1, name: 'Tag 1' },
    { id: 2, name: 'Tag 2' },
    { id: 3, name: 'Tag 3' }
]
```

wouldn't need to convert it to an array of strings in order to use ngTagsInput. That introduces a new problem, though. Since a tag now carries more information than just its "name", a user won't be able to create a new tag by simply typing a string. Adding a tag will only be possible by selecting an autocomplete suggestion.

**Comment by MrSam** [comment]
Probably late to the party, but whenever I get data from PHP and I don't need any keys I do what's called 'go from assoc to stupid'.

```
function drop_keys_from_object(items) {
    // go from assoc to stupid
    var filtered = [];
    angular.forEach(items, function(item) {
        filtered.push(item);
    });
    return filtered;
}
```
This way ngTagsInput is nice with your data. (and anything else that needs repeating in angular)

**Comment by pelted** [comment]
Just ran across this thread trying to find a way to unwrap the array of objects this thing is creating from our array of strings. Quickly reading through this I just don't understand why the decision was made to actually change the data structure of the ngModel source. It seems that since this is an input form wrapper it shouldn't be modifying the data format at all.
