### ISSUE TITLE
Feature request: Sort tags on input

### ISSUE THREAD

**Issue by Schwankenson** [mbenford/ngTagsInput#465]
Thank you for this great plugin! 

For my application, only the possibility to sort tags/tag objects in a defined way would be a great improvement. I think it`s possible to sort the tags by just removing and readd tags in the right order would be possible, but this was confusing to the user.

A great way of implementing this would be, if after the input of a new tag, it just moves to it`s position, like the mixitup plugin does it (when you click on asc/desc): http://jsfiddle.net/nlko/4dGxn/

**Comment by itanex** [comment]
Could you not just sort your tags collection?

**Comment by Schwankenson** [comment]
Yes, I already do this, it`s easy and works great. But it is confusing for the user, if he enters something and it`s at another position after he confirms. It would be great if it would fly to it`s new position with an animation.

**Comment by itanex** [comment]
Oh you want to get kha-crazy with the proces... hmmm

**Comment by mbenford** [comment]
Sorry for not replying sooner.

@itanex is right. If you sort your model the directive will re-render it accordingly. And to perform a fancy animation, I guess you can simply use [Angular's built-in animation capabilities](https://docs.angularjs.org/guide/animations).

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
