### ISSUE TITLE
Pasting Multiple comma separated values does not work 

### ISSUE THREAD

**Issue by mg-arrow** [mbenford/ngTagsInput#466]
I am trying to use your component to parse comma delimited list of values and create tags on paste.

Please find the plunker link below:

http://plnkr.co/edit/bDx54d?p=preview

It does not seem to work. I actually figured out that the issue is caused by the wrong option value passed. The components seems to think addOnPaste is set to false even though it is true.

Regards

Mikhail

**Comment by mbenford** [comment]
Sorry for not replying sooner.

Is that plunker correct? It seems to be the default ngTagsInput template without any modifications.

Anyway, I just tested the `addOnPaste` option and it worked just fine. Take a look [here](http://plnkr.co/edit/bDx54d?p=preview).

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
