### ISSUE TITLE
How do you do html5 validation on the tags-input field

### ISSUE THREAD

**Issue by achintgoel** [mbenford/ngTagsInput#467]
Is it possible to add a required field on the tags input so that the field is required?

**Comment by mbenford** [comment]
Sorry for not replying sooner.

Yes, you can add either `required` or `ng-required="true"` to the `tags-input` element:

```html
<form name="form">
  <tags-input ng-model="tags" name="tags" required></tags-input>
  <p>{{form.tags.$valid}}</p>
</form>
```
Plunker [here](http://plnkr.co/edit/qVaDmQwl8Lf7jSjxfudl?p=preview).

**Comment by ndelvalle** [comment]
Shouldn't the input be valid when $scope.tags = [] and input.$pristine is true? If not, how do i remove default validation to add a custom one?. Thanks.

**Comment by pratnala** [comment]
This doesn't work. Form submission happens even when tags-input is empty

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
