### ISSUE TITLE
Adding tags with Enter key doesn't work properly for new tags with autocomplete

### ISSUE THREAD

**Issue by brazorf** [mbenford/ngTagsInput#470]
I'm using tags-input with auto-complete directive.

``` html
<tags-input ng-model="selectedTags"
    display-property="name"
    on-tag-adding="onBeforeTagAdd($tag)"
    on-tag-added="onTagAdd($tag)"
    on-tag-removed="onTagRemove($tag)"
    placeholder="Digita tags"
    replace-spaces-with-dashes="false"
    add-on-space="false"
    add-on-blur="false"
    add-from-autocomplete-only="false">

<auto-complete source="autocompleteTags($query)" selectFirstMatch="false" debounce-delay="500"></auto-complete>
```

Steps to reproduce:
- Have your source callback to return ["Tag1", "Tag2"]
- Type "ag1" in the input field. The expected behaviour would be adding a new "ag1" tag
- Hit Enter

You'll see that "Tag1" is selected instead. Is this a bug, or a configuration problem of mine?

**Comment by kanagukrs** [comment]
I would like to mention one issue when you are using key-property, then if you want to add new tag, then you can't able to add more than one new tag, it will always throw invalid tag error

**Comment by Velron** [comment]
I noticed this as well. Setting select-first-match="false" on the auto-complete directive fixed this for me.

**Comment by hoxu** [comment]
We ran into this also, and indeed `select-first-match="false"` is the way to go. I don't think `select-first-match="true"` should be the default when `addFromAutocompleteOnly` is false.

Also, for changed defaults/functionality, I think it would be nice to have a more prominent notice in the changelog. That would help people spotting (and testing) potentially usability-breaking changes.

(Having said that, good work with the library, we have saved tons of time not having to write our own!)

**Comment by brazorf** [comment]
That doesn't work for me, even with `select-first-match="false"` it keeps adding the first match.

**Comment by jimmccarthy** [comment]
I am having this issue as well.  The bug I am running into is that I am creating tags that have two properties, an email attribute and a name.  The email attribute is set up as the key and the name is set up as the display value.  The problem is that when you create a new tag, it sets the "name" property only.

Then in tagIsValid it tries to validate the new tag by calling

 tiUtil.findInObjectArray(self.items, tag, options.keyProperty || options.displayProperty)

the problem is that that method ends up comparing the "key" attribute to the "name" attribute but there is no key attribute on the new tag so it is undefined.  The result is that it returns all new tags as invalid it there is at least one tag selected in the current input.

I think what we really need is to set the key and display value for new tags.  I tried doing this in 

on-tag-adding

to set the key and to match the display value.  That kind of works but ends up throwing a console error because it happens too late since onTagAdding gets called after findInObjectArray in isTagValid.

**Comment by jimmccarthy** [comment]
A proposed fix to this issue is to add this code in the self.add method after calling setTagText(tag, tagText):

            if (options.keyProperty && !tag[options.keyProperty]) {
                tag[options.keyProperty] = tagText;
            }

That fixed the issue for me.

**Comment by mbenford** [comment]
Sorry for not replying sooner.

@brazorf As @Velron already mentioned, setting `selectFirstMatch` as false should solve your problem. If you're still experiencing it, please create a plunker showing the issue. You can use [this template](http://plnkr.co/edit/tpl:93P2qxOjYmlcYSqDmo39).

@kanagukrs @jimmccarthy I'm aware of that bug. Will work on a solution for the next release.

@hoxu I agree that the current defaults of those options aren't the best combination. I think that just changing the default value of `selectFirstMatch` to `false` would be enough to prevent such problems. Regarding the CHANGELOG, do you think the way breaking changes are currently being reported is bad?

**Comment by hoxu** [comment]
Yes, changing default value of `selectFirstMatch` to `false` seems like a good idea - that would fix this issue.

The way Breaking Changes are reported in `CHANGELOG.md` currently is good. It's just that the `selectFirstMatch` feature defaulting to true (and thus "breaking" addition of new tags) would have probably warranted an entry in that section, but I guess it was just oversight.

Thanks!

**Comment by brazorf** [comment]
@mbenford There you go: http://plnkr.co/edit/p1DmunFqk24qihapqtNJ?p=preview

Steps to reproduce as from my opening post. `selectFirstMatch` is set to false.

**Comment by vellotis** [comment]
For html element you have to use dashed variant as "select-first-match" not "selectFirstMatch".

**Comment by mGuv** [comment]
@mbenford Is there a ticket for the issue when creating new tags when using key-property?

Just stumbled across the same issue (and interestingly with the same use case as @jimmccarthy) and have currently had to manually add a fix.

**Comment by vellotis** [comment]
Actually I had the exact problem. I ended up not using the key-property option.
I think that #422 addresses the issue. The https://github.com/mbenford/ngTagsInput/issues/422#issuecomment-99753340 is exactly what I experienced.

**Comment by brazorf** [comment]
@hoxu I think that was my mistake, using `select-first-match` instead of `selectFirstMatch ` seems to trigger the desired behaviour. Thank you mate

**Comment by hoxu** [comment]
>  mbenford commented on 18 Jul 
> @hoxu I agree that the current defaults of those options aren't the best combination. I think that just changing the default value of selectFirstMatch to false would be enough to prevent such problems.

@mbenford So I guess if that change is done, this issue can be closed?

**Comment by guilbep** [comment]
@mbenford Still have that bug on 3.0.0; @jimmccarthy proposal works; Here's my pull request: https://github.com/mbenford/ngTagsInput/pull/647 If I may improve on it in anyway; please tell me so. Thank you a lot for you work.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
