### ISSUE TITLE
is it possible to remove the hint after tag was added?

### ISSUE THREAD

**Issue by liadlivnat** [mbenford/ngTagsInput#475]
I want to remove the hind after one tag is added, is it possible?

**Comment by liadlivnat** [comment]
anyone ?? helo.....

**Comment by avaragado** [comment]
Perhaps you should post on Stack Overflow.

**Comment by liadlivnat** [comment]
@avaragado but this is relevant for who wrote this directive.

**Comment by mbenford** [comment]
Sorry for not replying sooner.

You mean the placeholder? If you do, then you can change it by turning [active interpolation](http://mbenford.github.io/ngTagsInput/documentation/global-configuration) on for that option, changing the default value to an empty string and conditionally setting the placeholder to whatever you like. [This plunker](http://plnkr.co/edit/exFCyo1bth9ZYFeTPGcQ?p=preview) shows how to do all of that.

Finally, @avaragado is right. Questions on *how* to use ngTagsInput belong in Stackoverflow. Just remember to use the `ng-tags-input` tag so I receive a notification. And, of course, the odds to get a quick response there are much better than here since your question would be visible to a greater number of people. :)

**Comment by liadlivnat** [comment]
Thanks, it work great!!

Liad Livnat.

W: http://liadlivnat.com
IN: http://linkedin.com/in/liadl
F:https://www.facebook.com/liad.livnat
T: 054-4302040

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
