### ISSUE TITLE
on-focus and on-blur events

### ISSUE THREAD

**Issue by eranimo** [mbenford/ngTagsInput#483]
...would be great.

**Comment by mbenford** [comment]
Sorry for not replying sooner.

ngTagsInput already supports both `ngFocus` and `ngBlur` directives. That should be better documented, I must admit it. :\

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
