### ISSUE TITLE
List the matched words only

### ISSUE THREAD

**Issue by jkpandiyan** [mbenford/ngTagsInput#485]
Hi, 

 I am using mbenford/ngTagsInput, i need to list out only matched for what i had typed, else need to show empty list. Please help soon...

**Comment by mbenford** [comment]
Sorry for not replying sooner.

You should use the autocomplete's `source` option to perform the filtering you want. Take a look at #351.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
