### ISSUE TITLE
Autocomplete not working properly on mobile device.

### ISSUE THREAD

**Issue by DharmendraVaishnav91** [mbenford/ngTagsInput#487]
I used ngTagsInput in ionic mobile app but there is issue in showing autocomplete suggestion list, suggestion list hides when click on back button. Is there any method to prevent this one ?

**Comment by mbenford** [comment]
Sorry for not replying sooner.

The autocomplete list is closed when the element loses focus, which is a standard behavior for this kind of UI component, as far as I know.

If that behavior isn't what you need, I suggest that you fork the main repo and change the code to suit your needs.

**Comment by PapsOu** [comment]
I've found a workaround for this unexpected behavior on mobiles devices (using ionic too).

Just change the placeholder css in order to trigger correctly the focus event :

```scss
.host {
    .tags {
        .input {
            width: 100% !important;
        }
    }
}
```
Without this css rule, only touch events made on the placeholder's text was firing the focus event.

Now the touch event on input (especially on the placeholder) triggers the focus event. With this css rule, the placeholder is using the full width of the input, but it can be managed with appropriate css rules or js stuffs to avoid this « new line ».

Hope this helps

@mbenford : maybe you can add an option to adapt the placeholder's width to avoid this unexpected behavior ?

**Comment by shyamal890** [comment]
@PapsOu Exactly! Only clicking on placeholder text was firing focus event. `width: 100%` worked however, it causes the input to jump to 2nd line incase there are selected tags.

This is what I did: 
1. Added `ng-click="ngTagFocus()"` on `tags-input`
2. Following code in a service:

```
ngTagFocus = ($event) => {
        var ele = $($event.target);
        if (ele.attr("ng-model") !== undefined || ele.hasClass("tags") || ele.hasClass("host")) {
            this.$timeout(() => {
                ele.find("input").focus();
            }, 200);
        }
        //console.log($event.target);
    }


```

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by fkamlesh** [comment]
Hello @mbenford,

Thanks for the ngTagsInput. I have same issue on android device.
Please implementing same like this :[http://plnkr.co/edit/MHLeFdiOISLrUWT8T4gA?p=preview](http://plnkr.co/edit/MHLeFdiOISLrUWT8T4gA?p=preview)

Please help.
