### ISSUE TITLE
tag is not getting added when I press space in android 4.4 devices

### ISSUE THREAD

**Issue by harshalsharma27** [mbenford/ngTagsInput#489]
I am facing critical issue while using ngTgsInput.
Whenever I press space, tag is not getting added in android device version 4.4. I have tried add-on-space="true", but didn't worked out. As soon as I lose focus from input, tag gets added.

I tried one approach:
checkTag = function($event){
if($event.keyCode == 32){
$(event).target.blur();
$(event).target.focus();
}
}
These function is called as ng-keypress="checkCode($event)"  from my HTML file.

Please help me out guys.
These is working fine in IOS and WIndows. And for Android version 4.1,4.2,4.3 as well.
Problem seems to be specific to 4.4 only.

Thanks,
Harshal

**Comment by T1m1** [comment]
+1

**Comment by cjz9032** [comment]
when I use it in the "WeChat" , space,comma's keycode is zero!!!

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
