### ISSUE TITLE
autocomplete: Show tags on focus, close dropdown on loss of hover.

### ISSUE THREAD

**Issue by Jakobovski** [mbenford/ngTagsInput#494]
It would be a nice option for autocomplete to show tags on focus and close dropdown on loss of hover.

Otherwise the user needs to click somewhere else for the menu to close.

**Comment by mbenford** [comment]
Sorry for not replying sooner.

I honestly have never seen that behavior in any autocomplete/dropdown list. But I don't mind ngTagsInput supporting that scenario as longs as it's opt-in. I'll add this to the backlog.

FWIW, the user can close the autocomplete list by doing one of the following things:

1. Clicking elsewhere on the page;
2. By pressing the escape key;
3. By selecting a suggestion.

**Comment by fyyyyy** [comment]
it makes sense as an alternative to multiselect, i would also like to see this

**Comment by MichaelTSS** [comment]
Thanks @Jakobovski for submitting this issue. It is a very surprising behavior.
Go to one of your demos or check out the attachment:
<img width="420" alt="screen shot 2016-10-21 at 9 23 04 am" src="http://g.recordit.co/VDIUlbDX5D.gif">

Add a country, and type enter. The tag is added, the lists opens again.
Now remove a country using the backspace key. The tag is removed, the lists does NOT open again.

@mbenford I think @Jakobovski and myself would like to have the list close itself after a tag is added.

Thanks,

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
