### ISSUE TITLE
ng-model-options getter and setters do not work.

### ISSUE THREAD

**Issue by steelsojka** [mbenford/ngTagsInput#495]
With the current way the directive uses `ngModel` as a 2 way data binding instead of setting the view value through the model controller, `ng-model-options="{getterSetter: true}"` does not work.

The directive will receive the function instead of the model value the getter returns.

``` html
<ng-tags-input ng-model="controller.tags" ng-model-options="{ getterSetter: true }"></ng-tags-input>
```

``` javascript
class ViewController {
    constructor() {
        this._tags = [];
    }

    // scope.tags in the ng-tags-directive will receive this function instead
   // of calling the getter/setter.
    tags(value) {
        if (value) {
            this._tags = value;
        }

        return this._tags;
    }
}
```

**Comment by mbenford** [comment]
I wish I could use `ngModel.$setViewValue()` instead of relying on a 2-way binding, but unfortunately the former doesn't work well with "reference" types (e.g. arrays and objects). If I were to use it, I would have to make a copy of the entire array of tags every time a tag is either added or removed in order to update the model, and I'm not very fond of that since it could introduce bugs into people's code.

I really wish `$setViewValue()` had a "force" argument so I could force an update. As a matter of fact, that argument existed in previous versions of Angular, but [they decided to remove it](https://github.com/angular/angular.js/issues/8481).

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
