### ISSUE TITLE
Invoke a scope method in the ngTagsInput template

### ISSUE THREAD

**Issue by beradrian** [mbenford/ngTagsInput#500]
At this moment it is not possible to do something like this

```
<script id="tagTemplate" type="text/ng-template">
     <div>
        <span>{{$getDisplayText()}}</span>
        <button ng-click='showDetails(data)'>More</button>
     </div>
</script>
```

if the `showDetails(tag)` is a method defined in the scope.
See the entire discussion here: http://stackoverflow.com/questions/31042868/is-it-possible-to-invoke-a-scope-method-in-the-ngtagsinput-template

**Comment by mbenford** [comment]
Sorry for not replying sooner.

That makes sense. I'll add it to the backlog.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
