### ISSUE TITLE
"disabled" attirbute still allows full functionality

### ISSUE THREAD

**Issue by bucs-fan813** [mbenford/ngTagsInput#502]
Adding a "disabled" attribute will grey out the input box but still allows for the autocomplete query and tags to be entered as usual.

**Comment by jbfresh** [comment]
ng-disabled="true" seems to work. Is this a feature or a flaw??

**Comment by mbenford** [comment]
Sorry for not replying sooner.

Could you provide a plunker showing the problem? You can use [this template(http://plnkr.co/edit/tpl:93P2qxOjYmlcYSqDmo39).

**Comment by jbfresh** [comment]
No worries. I have updated the plunker (
http://plnkr.co/edit/rWgdaSRfAdTBpT3BiYzw?p=preview). When I add disabled
to "<tags-input... ...disabled>" the input fields appears to be disabled
but you can still add and remove tags.

V/R
John

On Mon, Sep 28, 2015 at 9:14 AM, Michael Benford <notifications@github.com>
wrote:

> Sorry for not replying sooner.
>
> Could you provide a plunker showing the problem? You can use [this
> template(http://plnkr.co/edit/tpl:93P2qxOjYmlcYSqDmo39).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbenford/ngTagsInput/issues/502#issuecomment-143739989>
> .
>



-- 
"It's better to be boldly decisive and risk being wrong than to agonize at
length and be right too late."
Marilyn Moats Kennedy

**Comment by mbenford** [comment]
For your markup to work with ngTagsInput it should be either 

```html
<tags-input ng-model="tags" disabled="any-value">
```
or (recommended)
```html
<tags-input ng-model="tags" ng-disabled="true">
```

I understand that `<tags-input ng-model="tags" disabled>` is valid HTML5, but I assumed most people would use Angular's `ngDisabled` directive instead of manually adding the `disabled` attribute, and that directive works by adding `disabled="disabled"`.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
