### ISSUE TITLE
Store only id in model, pull name from autocomplete source

### ISSUE THREAD

**Issue by gildebrand** [mbenford/ngTagsInput#504]
I have an autocomplete source that looks like this `[{id: 1, name: 'Tomatoes', id: 2, name: 'Bananas'}]`.
Right now when I choose an element from the autocomplete list, the entire object with _both_ id and name get added to the model of tags-input. However, I would like to only store the id in the model of tags-input, and make tags-input pull the name from the autocomplete source. Is this possible somehow?

**Comment by jacquesdancona** [comment]
+1

**Comment by evillemez** [comment]
+1 Also looking for a simple way to do this... toying with the idea of a wrapping directive to transforms the model and what not, but it feels like a hack.

**Comment by jacquesdancona** [comment]
@evillemez That's what I'm currently doing, passing ngModel on to ngTagsInput. The parent directive uses its own $formatters and $parsers for manipulating the passed ngModel and viewValue.

**Comment by mbenford** [comment]
Sorry for not replying sooner.

There's no built-in support for that, but I think using $parsers/$formatters, as @jacquesdancona suggested, is the correct solution since that's precisely what they are meant to do.

If someone is successfully using that approach and is willing to share it, let me know and I'll add it to the Demos page on ngTagsInput website.

**Comment by jacquesdancona** [comment]
@mbenford I'll post a plunkr today or tomorrow.

**Comment by AlexanderKozhevin** [comment]
+1

**Comment by jukkasi** [comment]
+1 for this. The hacks required a) to make model contain only ids (strings in this case) are horrible.

Related to this, b) there should be more flexible way to display tag names. Current displayProperty is not enough since for translations etc. it would need to be a function expression.

Summarizing these two problems I feel that the initial approach should have been something like ng-options is. This approach is used by angular strap select for example.

This way it would be possible to a) define expression for binding selected tags to model and b) define expression for displaying tags

**Comment by andrewfrankel** [comment]
@jacquesdancona, working through a similar issue, did you have a chance to post that plunkr?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
