### ISSUE TITLE
Checking for leftover text

### ISSUE THREAD

**Issue by bgold0** [mbenford/ngTagsInput#506]
When a form is invalid, I make my submit button opaque like so:

```
<button type="submit" ng-class="(!form_name.$valid) ? 'opacity2' : ''">
```

However when:
- **Tag box is focused**: form is valid with `ng-valid-leftover-text`
- **Tag box us unfocused**: form is invalid with `ng-invalid-leftover-text`

Is there a way to check to see if there is leftover text so I can add that to my `ng-class` to make it so it's opaque. Obviously when I click on the button it won't submit since it unfocuses from the tag box but I don't want to give the user the impression that the form is valid with leftover text.

**Comment by mbenford** [comment]
Sorry for not replying sooner.

As of v3.0 you can access the inner's input value by using the `text` option:

```html
<tags-input ng-model="tags" text="text"></tags-input>
```

See [this plunker](http://plnkr.co/edit/q2h9yyokxXZmxOxe5TKD?p=preview).

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
