### ISSUE TITLE
Bug in addFromAutocompleteOnly

### ISSUE THREAD

**Issue by kimcrab** [mbenford/ngTagsInput#508]
addFromAutocompleteOnly works perfect except the first tag. 
I can put anything on the first tag even if " "addFromAutocompleteOnly = true" 
Can you guess why it happens?

EDIT: It's not the first tag.
          I tried many situations and found out that I can always type only one tag which is not on the autocomplete list. 
It seems like addFromAutocompleteOnly works after one unlisted tag is added.

**Comment by mbenford** [comment]
Sorry for not replying sooner.

Could you provide a plunker showing your issue? I wasn't able to reproduce it.

You can use [this template](plnkr.co/edit/tpl:93P2qxOjYmlcYSqDmo39).

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
