### ISSUE TITLE
Autocomplete is too generic name for a directive in a library

### ISSUE THREAD

**Issue by crisguitar** [mbenford/ngTagsInput#510]
I have a pretty big application with tons of custom directives and I had a conflict because of the "autocomplete" directive. I personally think "autocomplete" is too generic name to be part of a library. If someone else agrees with me I am happy to do the pull request.

**Comment by diablouma** [comment]
I think that directive should have a more descriptive name in order to be clear about its purpose, because autocomplete is used as name for a bunch of another directives for angular.

**Comment by mbenford** [comment]
Sorry for not replying sooner.

The `autoComplete` directive only works within a `<tags-input></tags-input>` element, so it shouldn't conflict with another directives that happen to have the same name. Note that I said *it shouldn't*, because I just took a look at the code and there's no check in place for that and it's definitely a bug.

About the name itself, I personally think it's just right for the context in which the directive is supposed to be used, which is along with the `<tags-input>` element. Context matters in this case.

But I agree that, as custom elements become more widespread, name clash will be a real issue, and I've been thinking of providing a way for the user to change the name of both directives without having to tweak the source code. I'll update this issue as soon as that feature is available.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
