### ISSUE TITLE
Mozilla Firefox Issue: Selection is not working properly from the drop-down list

### ISSUE THREAD

**Issue by sravankumaroneness** [mbenford/ngTagsInput#511]
Once I selected the drop-down in Mozilla Firefox, I am not able to see what i selected and the ng-model also not updating.

It is not working only in Mozilla-Firefox

**Comment by mbenford** [comment]
Sorry for not replying sooner.

Please take a look at #262. It seems to be the same issue as yours.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
