### ISSUE TITLE
Is it possible to show values programmatically?

### ISSUE THREAD

**Issue by vdzundza** [mbenford/ngTagsInput#514]
Hi all,

I want to show autocomplete results after clicking on button? I've found load-on-focus parameter. How can I show results on an event, for example, load-on-event="OPEN_SUGGESTION" ?

**Comment by yhourdel** [comment]
Hi,

I've written a directive to do such a thing and integrated it as a bootstrap feedback:

```jade
.form-group.has-feedback
  label.col-sm-3.control-label(for='tags') Tags
  .col-sm-8

    //- input
    tags-input(
      id="tags"
      name="tags"
      ng-model="contact.tags"
      placeholder="Add a tag"
    )
      auto-complete(source="autocompleteTags($query)")

    //- trigger
    .form-control-feedback.clickable(auto-complete-trigger)
      .caret(ng-if="!autocompleting")
      i.fa.fa-refresh.fa-spin(ng-if="autocompleting")
```

(my `autocompleteTags` function sets `autocompleting` to true while working)

```coffeescript
app.directive 'autoCompleteTrigger', ->

  restrict: 'EA'
  link: ($scope, $el, attrs)->

    $el.click ->
      $input = $el.prev().find('input').first()
      tagsInput = angular.element($input).scope()
      suggestionList = angular.element($el.prev().find('auto-complete').children().first()).scope().suggestionList
      $input[0].focus()
      suggestionList.load(tagsInput.newTag.text, tagsInput.tagList.items)
```

If it makes sense, I can bundle it in a pull request

**Comment by vdzundza** [comment]
Yeah, It looks great. Thanks a lot.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
