### ISSUE TITLE
  Multiple tag inputs within single page

### ISSUE THREAD

**Issue by sprakashg** [mbenford/ngTagsInput#515]
It doesn't work if I use with autocomplete. here is an example and the error shown in console.
"TypeError: a.filter is not a function"

```
        <label class="control-label pull-left" style="padding: 10px;line-height: 30px;" ng-show=" promo_action_option =='Sale'">Link to a Sale</label>
                  <tags-input ng-model="tags" placeholder="Link to a sale" display-property="label" on-tag-added="tagAdded($tag)" on-tag-removed="tagRemoved($tag)" ng-show=" promo_action_option =='Sale'" style="margin-top:5px;" id="id1">
                  <auto-complete source="loadTags($query)"></auto-complete>
                  </tags-input>
                  </p>

                  <p>

                    <label class="control-label pull-left" style="padding: 10px;line-height: 15px;" ng-show="promo_action_option =='Category'">Link to a Category</label>
                    <tags-input ng-model="sales" placeholder="Link to a Category" display-property="label" ng-show=" promo_action_option =='Category'" style="margin-top:5px;"  id="id2">
                      <auto-complete source="loadSales($query)"></auto-complete>
                    </tags-input>
```

**Comment by mbenford** [comment]
Sorry for not replying sooner.

Without seeing your code, it's hard to tell what the problem is. I guess your `loadTags()` function is returning an invalid value and thus the `autoComplete` directive fails to process it.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
