### ISSUE TITLE
Free text with optional tagging

### ISSUE THREAD

**Issue by TomRaz** [mbenford/ngTagsInput#520]
Hey,
I need to implement a tagging text input, but with optional free text between the tags.
I need the text to be editable normally, and optionally tag some values depending on the user selection(choosing from the auto complete for example). 
For example, the text can be a user status, and the user can tag his friends in the status, the rest of the text should be just normal text.
It should be a similar behavior as facebook hashtags, or jira people/bugs tagging.  

It would also be nice if I could add tags programmatically, but it's not a must.
Is there any way to do this with ng-tags-input?

Thanks!

**Comment by mbenford** [comment]
Sorry for not replying sooner.

That's beyond what ngTagsInput can do. You should use an appropriate component for that task, like [this one](https://github.com/jeff-collins/ment.io).

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
