### ISSUE TITLE
For meteor, depend on angular:angular, not angularjs:angular?

### ISSUE THREAD

**Issue by estaub** [mbenford/ngTagsInput#522]
In the meteor packaging, urigo:angular (Angular-Meteor) depends on angular:angular, and ngTagsInput depends on angularjs:angular, resulting in a double load and "Tried to load angular more than once."  See http://stackoverflow.com/questions/32100391/angular-dependency-conflict-on-meteor-organizations-angularjs-and-angular .

**Comment by mbenford** [comment]
Sorry for not replying sooner.

There's no official package for Meteor right now. If you're using one, it wasn't created/published by me.  Perhaps you could try to contact the author of that package?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
