### ISSUE TITLE
Unable to return data object from response/promise

### ISSUE THREAD

**Issue by bucs-fan813** [mbenford/ngTagsInput#527]
I'm not sure if this would improve error handling but can I return just the data object on success? The following code will not work but hopefully the idea makes sense.

``` javascript
$scope.loadTags= function (query) {
 $http.get('types.json').success(
  function (data, status, headers, config) {
    console.log(config);
    console.log(data);
    console.log(status);
    console.log(headers);
    return data;
    //currently have to return $http.get('types.json') in order for code to work but this is not ideal.
   }).error(
   function (data, status, headers, config) {
    //Handle Errors
   }).then(
   function (data, status, headers, config) {
    //Handle cleanup
   });
};
```

**Comment by mbenford** [comment]
Sorry for not replying sooner.

ngTagsInput will work with any array that your success callback may return, but you need to make your `loadTags()` function return a promise:

```javascript
$scope.loadTags= function(query) {
  return $http.get('types.json').success(function(data) {
    return data;
  });
};
```

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
