### ISSUE TITLE
filter autocomplete by multiple model property

### ISSUE THREAD

**Issue by liadlivnat** [mbenford/ngTagsInput#528]
Hi,
How can i filter the results by few properties,

Let say the model is
$scope.person = {age:40,sex:man,color:black}

currently the autocomplete filter only by display-property, but i would like to filter also by sex and color.

is it possible?

**Comment by mbenford** [comment]
Sorry for not replying sooner.

What exactly do you mean by *"the autocomplete filter only by display-property"*?

**Comment by kukac7** [comment]
I understand, I have a similar problem.
````
display-property="(last_name + ', ' +first_name)"
````
I want you to look for the autocomplate between the first name and the last name.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
