### ISSUE TITLE
Autofocus and removeTag issue

### ISSUE THREAD

**Issue by kotmatpockuh** [mbenford/ngTagsInput#529]
Hello.

Steps to reproduce:

set loadOnFocus = true

1) add ngTagsInput with data, save, and reload page.
2) Click on one of the tags (on close) to remove the tag

Actual result: suggestion list appear
Expected result: suggestion list appear only after click in tags area or at add tag placeholder

**Comment by mbenford** [comment]
Sorry for not replying sooner.

The autocomplete will only be automatically displayed if both `loadOnFocus` and `loadOnEmpty` options are true. If only `loadOnFocus` is set as true, the suggestion list won't be rendered upon clicking on any part of the element, as you can see in [this plunker](http://plnkr.co/edit/5O4ope1hgQyKb9Iswkvj?p=preview).

If you're experiencing a different behavior, please provide a plunker script showing the issue. You can use [this template](plnkr.co/edit/tpl:93P2qxOjYmlcYSqDmo39).

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
