### ISSUE TITLE
class title `tags` is too general

### ISSUE THREAD

**Issue by farhansalam** [mbenford/ngTagsInput#530]
class title `tags` is too general it could be something line `ti-tags`. This goes `tags-list` as well. Because it is conflicting with our app's css.

**Comment by mbenford** [comment]
Sorry for not replying sooner.

Is it ngTagsInput's stylesheet that's conflicting with your app's CSS or is it the other way around? I mean, I can see some `tags` class messing with the `tags-input` element, but the opposite shouldn't happen.

Just to be clear, I agree that ideally no conflict should exist whatsoever. I just want to understand exactly the issue you're experiencing.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
