### ISSUE TITLE
Using in Ionic framework show & hide mobile keys quickly

### ISSUE THREAD

**Issue by mkj-git** [mbenford/ngTagsInput#536]
I am using ngTagsInput with ionic framework. The problem is if i press on textbox it show & hide the mobile keys so i am not able to type anything. When i do long pressing (like we do long press for paste) then it show mobile keys.

**Comment by mstmustisnt** [comment]
Facing the same problem...

**Comment by SebastianSchenk** [comment]
Some here!!

**Comment by ace-han** [comment]
Facing the same problem!!!

However, a temp solution could be found in #487.
And I think that css rule can take care the situation mentioned in #217, #487, #496, #536.

**Comment by shyamal890** [comment]
@ace-han Were you able to make ng-tags work alright on mobile phone?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
