### ISSUE TITLE
How to disable adding tag

### ISSUE THREAD

**Issue by kurtuluso** [mbenford/ngTagsInput#537]
Hi,
Thank you for this great widget.

Unfortunately I do not like the mobile performance of the widget and I want to open a new screen for just adding a single tag.

For this purpose, I have to disable adding and allow removing tags.

How can I do this? If there is no way, accept this issue as a improvement suggestion

**Comment by mbenford** [comment]
Sorry for not replying sooner.

If you want to prevent the user from adding tags, but let her remove existing ones, you can do something like this:

```html
<tags-input ng-model="tags" on-tag-adding="false"></tags-input>
```

About the directive's performance, I have never thoroughly tested it on mobile devices, so I'm sure there's room for improvement. I'd appreciate if you could provide more information on any performance bottleneck you may have noticed.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by softengi** [comment]
On setting the option on-tag-adding to false, the control will not add the new tag on pressing Enter, but will still allow the user to type the word in the textbox.
I need to add the tags from code/from another control on the page and let the user delete the tags from this control.
Is there a way I can disable this control or not allow focus in the input box and still allow tag removals?

Thanks in advance.
