### ISSUE TITLE
Suggestion List does not disappear after focus out

### ISSUE THREAD

**Issue by kurtuluso** [mbenford/ngTagsInput#538]
I have the following configuration:

``` html
<tags-input ng-model="query_circles" placeholder="Çevre Seçiniz" display-property="name" replace-spaces-with-dashes="false" min-length="1" add-from-autocomplete-only="true"  add-on-blur="false">
    <auto-complete source="cevrelisteleForSearch()" load-on-empty="true" load-on-focus="true" select-first-match="false"></auto-complete>
</tags-input>
```

Problem:
When I select from suggestion list, list remains open => OK.
But when I click on outside, the list does not disappear.

Screen Video: http://www.screencast.com/t/MYs22KwT

Installed Version: 3
I've made a fix on 2.3 but I my solution did not work with new version.

Thanks

**Comment by mbenford** [comment]
Sorry for not replying sooner.

That's odd. The autocomplete list should be closed as soon as the element loses focus. 

I wonder if you could provide a plunker showing the problem you're experiencing? You can use [this template](plnkr.co/edit/tpl:93P2qxOjYmlcYSqDmo39).

**Comment by Sennahoi** [comment]
I've got the same problem with the example on the main page: http://mbenford.github.io/ngTagsInput/
Steps to reproduce with Chrome on Windows:

1. Click in text field so that it gets the focus
2. Cursor down
3. Click on the Scroll down button (arrow down) of the suggestion list (text field looses focus, suggestions list is still there)
4. Now, you can click everywhere and the suggestion list doesn't disappear.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
