### ISSUE TITLE
Why not use variables in /scss/bootstrap.scss

### ISSUE THREAD

**Issue by CraryPrimitiveMan** [mbenford/ngTagsInput#539]
Why not define the color variables in bootstrap.scss file?

``` scss
//** Border color for inputs on focus
$input-border-focus:             #66afe9;
```

**Comment by mbenford** [comment]
Sorry for not replying sooner.

There's no reason not to use variables. I was probably just lazy back when I wrote the SCSS file for Bootstrap.

PRs are welcomed. :smile:

**Comment by xnog** [comment]
+1

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
