### ISSUE TITLE
In ngTagsInput how to show validation message for different cases?

### ISSUE THREAD

**Issue by manisankar92** [mbenford/ngTagsInput#541]
I am using ngTagsInput Angular plugin for getting multiple email ids.
In my code 3 validation has been added those are as follows:
    1.For Mandatory fields.
    2.Field should accept only an email id.
    3.It should not allow duplicate email id.

The above cases are working fine. But, I want to show the error message dynamically according to the above one of the case has occurred. Please help me out !!!

**Comment by mbenford** [comment]
ngTagsInput uses `ngModelController` to set form's validity, so you can validate it as you would do with any form. Take a look at [this post](https://scotch.io/tutorials/angularjs-form-validation).

**Comment by uhtred** [comment]
Don't get it how to validate ng-tags using ng-messages, required for example. Can you help me?

**Comment by uhtred** [comment]
Sorry, my fault, your directive accept name attribute. Thanks a lot, awesome code.

**Comment by SangameshPH** [comment]
But when you add required == true. By default the control is in Error state.
When I checked in in DOM, the state was ng-invalid ng-invalid-required, even though I havent touched the element. Seems strange. Can you help me?

Thanks,
-/Sammi

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
