### ISSUE TITLE
Autocomplete window won't show up

### ISSUE THREAD

**Issue by littleneotrix** [mbenford/ngTagsInput#542]
Hi,
I'm having an issue with the auto-complete window that won't show up.

This is my code that loads the list and filters by the 'query' that NG sends:

``` javascript
    $scope.loadGenres = function ($query) {
        return $http.get('/ajax/get_genres', { cache: true }).then(function (response) {
            var genres = response.data;
            return genres.filter(function (genre) {
                return genre.genre.toLowerCase().indexOf($query.toLowerCase()) != -1;
            });
        });
    };
```

And that's my HTML code itself:

```
<tags-input ng-model="genres" add-on-comma="false">
  <auto-complete source="loadGenres($query)"></auto-complete>
</tags-input>
```

When I'm using the tags input in the console itself I can see it found matches, here you can see it here:
![Image](https://i.gyazo.com/a22289ee03c5ee79977b38f808315ac8.png)

And what happens when I'm writing something & there's a match:
![Image](http://i.imgur.com/OCvmlo4.png)

As you can see a small window that should be the auto-complete window is getting opened when there are matching results, but can't see anything.
I tried via the Chrome Console to change it's CSS to make it bigger, but it's empty inside.

Any ideas?

Thanks!

**Comment by mbenford** [comment]
By default, both directives (`tagsInput` and `autoComplete`) expect each tag object to have a property named `text` that is used for displaying the tag. Since your object doesn't have a property with that name, you need to tell the directive to use a different one:

```html
<tags-input ng-model="genres" add-on-comma="false" display-property="genre">
  <auto-complete source="loadGenres($query)"></auto-complete>
</tags-input>
```

Since the object you're using has an `id` property, perhaps you should set the `keyProperty` option as well. Take a look at [the docs](http://mbenford.github.io/ngTagsInput/documentation/api) for more information.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
