### ISSUE TITLE
addOnBlur does not select first item from autocomplete

### ISSUE THREAD

**Issue by danielyaa5** [mbenford/ngTagsInput#547]
How can I have the first option from autocomplete selected when the input field loses focus?

**Comment by mbenford** [comment]
That's no way to do that right now. `addOnBlur` only tells the directive to add the text left in the input as a tag.

I guess the best you can do is fork this repo and change the code to suit your needs.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
