### ISSUE TITLE
semicolon delimited text

### ISSUE THREAD

**Issue by chetanra** [mbenford/ngTagsInput#548]
My backend has a bunch of text that are semicolon delimited.  Is there a way to configure the tagsinput to parse this text to display the tags?

**Comment by mbenford** [comment]
There's no built-in way to do that. I suggest you split the text before assigning it to the `tags-input` element.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
