### ISSUE TITLE
Travis build broken

### ISSUE THREAD

**Issue by Tim-Erwin** [mbenford/ngTagsInput#550]
Although only changing little things in the code in the latest PRs the following error occurs:

```
Loading "compress.js" tasks...ERROR
>> Error: Cannot find module 'ansi-regex'
Warning: Task "compress" not found. Use --force to continue.
```

I cannot see how this should be any related to the PRs.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
