### ISSUE TITLE
Bug: If the Tag display property is too long, it causes UI issue

### ISSUE THREAD

**Issue by shyamal890** [mbenford/ngTagsInput#555]
Check out this plunker http://plnkr.co/edit/wUd2gf?p=preview . When the text is too long that it overflows the input component the UI for 2nd line breaks.

Suggestion: There must be a trim-length property that can be set for display text. 
(I hope I haven't missed this property in the documentation.)

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by shyamal890** [comment]
This issue is still there
