### ISSUE TITLE
Disable typing?

### ISSUE THREAD

**Issue by markwpearce** [mbenford/ngTagsInput#556]
I'm using ng-tags-input in other locations in my app, but I have a use case where I want it to have the close buttons, but not allow the user to type anything.

I can't just ng-disabled="true" the input, because I still want the user to be able to click the little x button to close them, and it doesn't show up when it's disabled. I also want the tags to have the "enabled" look to them...

**Comment by mbenford** [comment]
You could use the `onTagAdding` option:

```html
<tags-input ng-model="tags" on-tag-adding="false"></tags-input>
```

That'll prevent any tag from being added yet allowing existing ones to be removed.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
