### ISSUE TITLE
Bootstrap theme reliying on CSS import order cause problem with JSPM

### ISSUE THREAD

**Issue by davinkevin** [mbenford/ngTagsInput#559]
Hi, 

First of all, thanks for your lib, I really like it and use it on many project.

But right now, I have a problem. I use JSPM to build my application and bundle it for my prod environnement and I also use bootstrap for my style. So, I would like to use the specific themes of NgTagsInput for bootstrap, but you rely on the CSS import order to apply correct styling, witch is not good in JSPM, because we can't control the import order in such build scenario (we end up with one huge CSS with every CSS imported by our JS.

The simplest (and maybe best) solution if we want to override a css style is to use a more specific css selector. We do that when we want to override some external CSS by adding a prefix to our CSS via LESS or SASS (basically .name-of-our-app) and add it on the <html> block.

I think, it should be good to use the same pattern to apply bootstrap theme. We could simply add a bootstrap-v3 (for example) css class to the tags-input and all the css class in the ng-tags-input.bootstrap.min.css could be prefixed by this class.

With that, no more CSS order, no more random CSS behavior.

Do you think it's possible ? Do I miss something which fix simply that problem ? 

Thanks for your help.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by davinkevin** [comment]
I think this issue should be reopened. 

It will also help the migrate the lib to a `ES2015` standard...
