### ISSUE TITLE
Empty input on load. Choosing tags from select.

### ISSUE THREAD

**Issue by imaginalis** [mbenford/ngTagsInput#562]
Hello.
Thanks for your great plugin. Is there any way to initialize tags input without populating it?
I've got my model and I want to let user to choose tags from select(suggester). But on page load I would like to have just empty field.

Is there any way to 'invert' your plugin initalization?

Thanks!

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
