### ISSUE TITLE
Object "template" for new tags

### ISSUE THREAD

**Issue by AndrewIsh** [mbenford/ngTagsInput#563]
As demonstrated in the "Tags input with custom objects" Plunker, it's possible for tag objects to consist of a number of properties. However, when adding new tags to the array, the objects only consist of the tag name.

It would be useful to be able to specify properties that a new tag object should contain. My use case is that I would like all new tags to contain an 'id' property of null, which is what my API is expecting.

Currently, I've got an on-tag-added callback that manually assigns it an ID of null, but this feels rather hackish. Being able to say "all new tags should have these properties in addition to the name" feels so much cleaner.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by akhilpgeorge** [comment]
@AndrewIsh @mbenford is there any way to achieve custom object for a new tag?
