### ISSUE TITLE
Min line-height of input is 2 in firefox

### ISSUE THREAD

**Issue by Psytrooper** [mbenford/ngTagsInput#565]
Currently when using ngTagsInput in firefox the input field occupies 2 line when in safari it only occupies 1. From what I can gather it appears that a ul element is the reason for this and should probably not be displayed.
![screen shot 2015-11-13 at 4 47 28 pm](https://cloud.githubusercontent.com/assets/1610879/11148656/a20d7016-8a26-11e5-8d3e-40e82ac7fbf4.png)
![screen shot 2015-11-13 at 4 48 01 pm](https://cloud.githubusercontent.com/assets/1610879/11148661/a8e12298-8a26-11e5-90b7-a942930211b6.png)

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
