### ISSUE TITLE
Read only or disable edit

### ISSUE THREAD

**Issue by fanpes** [mbenford/ngTagsInput#566]
Is there a way that only you can read the labels but can not be edited in any way?
Not add new ,  delete existent or edit any tags

**Comment by DavidBernal** [comment]
+1

**Comment by pratik14** [comment]
@fanpes @DavidBernal Can use CSS to do this. Add "pointer-events: none;" style to "tags-input" html element.

**Comment by jakobmaier** [comment]
Duplicate: https://github.com/mbenford/ngTagsInput/issues/241

**Comment by mertenhanisch** [comment]
It is not explicitly stated in the documentation, but you can do `<tags-input disabled="true"></tags-input>` which will work.

**Comment by shyamal890** [comment]
@mertenhanisch I think what @fanpes and @DavidBernal are saying is how to disable individual tags and keep the rest editable.

I too need the same feature, disable tags on a condition.

**Comment by geoguide** [comment]
@mertenhanisch That doesn't quite work as expected either. It just disables it no matter what. It should take an expression that can be evaluated.

**Comment by jdmichaud** [comment]
What can be done is (in Less):
``` less
.read-only {
  .remove-button {
    display: none
  }
}
```
Then use `tag-class` attribute to set the `read-only` class to the particular tag.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
