### ISSUE TITLE
bower invalid-meta is missing "ignore" entry in bower.json

### ISSUE THREAD

**Issue by rmariuzzo** [mbenford/ngTagsInput#571]
Hey team!

I appreciate all your work on this very useful component! **This issue isn't a blocker**.

When I installed this via Bower, I got the following warning:

``` sh
bower invalid-meta  ng-tags-input is missing "ignore" entry in bower.json
```

Full output:

``` sh
$ bower install ng-tags-input --save
bower not-cached    git://github.com/mbenford/ngTagsInput-bower.git#*
bower resolve       git://github.com/mbenford/ngTagsInput-bower.git#*
bower download      https://github.com/mbenford/ngTagsInput-bower/archive/v3.0.0.tar.gz
bower extract       ng-tags-input#* archive.tar.gz
bower invalid-meta  ng-tags-input is missing "ignore" entry in bower.json
bower resolved      git://github.com/mbenford/ngTagsInput-bower.git#3.0.0
bower install       ng-tags-input#3.0.0
```

**Comment by mblascoespar** [comment]
Could reproduce it too!

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
