### ISSUE TITLE
$scope is not available inside ng-templates for autocomplete or tags)

### ISSUE THREAD

**Issue by mikekoro** [mbenford/ngTagsInput#572]

**Comment by theBull** [comment]
+1

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
