### ISSUE TITLE
when double click, it wont go to the edit. Is there any options that enable it? or is it a issue?

### ISSUE THREAD

**Issue by ravindueranga** [mbenford/ngTagsInput#573]

**Comment by hmontazeri** [comment]
+1

**Comment by nevedimko** [comment]
+1

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
