### ISSUE TITLE
Unexpected behaviour when select-first-match is false on autocomplete

### ISSUE THREAD

**Issue by brazorf** [mbenford/ngTagsInput#575]
Assume i've the following entries as the autocomplete source

``` javascript
 var tags = [
    { id: 1, name: 'Tag1' },
    { id: 2, name: 'Tag2' }
  ];
```

If i type `tag1` and `select-first-match=false` i have two different behaviours for the same tag.

Case 1) I select the matching `Tag1` by click: the full tag object is stored to the `ng-model`

``` javascript
 [{ id: 1, name: 'Tag1' }]
```

Case 2) I hit enter: a tag with only the `display-property` is added to the `ng-model`

``` javascript
 [{name: 'Tag1' }]
```

In my opinion, _case 1_ is the expected behaviour while _case 2_ is not.
This might be a problem when you have to make the decision whether to insert a new tag or not.

I think the design behaviour should be, regardless of the `select-first-match` option,   something like
- tag is clicked from dropdown: add it to the ng-model array
- enter is hit: an item with the same `display-property` as the typed one should be searched in the source and eventually be added to the ng-model

What are your thoughts about this?

**Comment by brazorf** [comment]
See [plunker here](http://plnkr.co/edit/5GMRbbA2TqIyIa65fbEF?p=preview)

**Comment by bobzhang199102** [comment]
@brazorf , the autocomplete can only highlight the selected tags. It cannot show only the selected tags. Do you know how to solve this? Thanks

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
