### ISSUE TITLE
A small fix for input of Chinese characters

### ISSUE THREAD

**Issue by leechenhwa** [mbenford/ngTagsInput#576]
As the difference of Chinese language and English language, many Chinese words are made of two Chinese characters, and there may be tags with only one Chinese character. So here is the startpoint for the fix: bypass the minLength validation if any non-alphnum found.

``` javascript
tagIsValid = function(tag) {
            var tagText = getTagText(tag);

            return tagText &&
                   (tagText.length >= options.minLength || (tagText.length > 0 && /[^0-9a-zA-Z]+/.test(tagText)) ) &&
                   tagText.length <= options.maxLength &&
                   options.allowedTagsPattern.test(tagText) &&
                   !tiUtil.findInObjectArray(self.items, tag, options.keyProperty || options.displayProperty) &&
                   onTagAdding({ $tag: tag });
        };
```

**Comment by cjz9032** [comment]
chinese spellcheck also doesn't work :dash:

**Comment by indianazhao** [comment]
@leechenhwa, thank you! This fix works for me!

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
