### ISSUE TITLE
Loading div in autocomplete on http request

### ISSUE THREAD

**Issue by shyamal890** [mbenford/ngTagsInput#578]
When a http request is made for getting tags from server the autocomplete should show a loading div so that the user is not stumped in case of delayed response.

Example in which the http request takes 5 secs to respond: http://plnkr.co/edit/QvWbTB?p=preview

**Comment by shyamal890** [comment]
@mbenford Can you have a look at this issue.

**Comment by skidvd** [comment]
+1

**Comment by shyamal890** [comment]
@skidvd This is too easy to implement. May be we can even expose a `loadingTemplateUrl` attribute for user to customize.  Hope @mbenford would see value in it.

**Comment by natan88** [comment]
+

**Comment by Smiley01987** [comment]
+1

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by shyamal890** [comment]
This is a must have feature. Please consider reopening this issue.
