### ISSUE TITLE
transcludeFn is not a function

### ISSUE THREAD

**Issue by danielmcquillen** [mbenford/ngTagsInput#579]
I wanted to update the default template with a bit of extra code that styles the tag color a certain way.

To begin, I just tried copying the templates/tags-input.html file into a different directly (without even modifying it) and then adding an attribute to my tags-input...

```
 <tags-input id="tagsInput"  template="/some/direct/path/partials/custom_ng_tags_input.html"
```

However, when I run the app I get a "transcludeFn is not a function" error

```
TypeError: transcludeFn is not a function
    at http://localhost:8888/static/vendors/bower_components/ng-tags-input/ng-tags-input.js:823:9
```

Any thoughts on something I'm overlooking or might have done wrong? 

(Many thanks @mbendford for this really helpful library.)

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
