### ISSUE TITLE
unable to disable auto resize of textbox

### ISSUE THREAD

**Issue by adithyasai** [mbenford/ngTagsInput#581]
I dont want the tags to be with in the input field and so iam placing them out of the input filed. and when i type something on the input filed it is resizing the texbox. and i dont want that to happen. i have tried couple of solution to stop the autosize but none of them worked. how to stop "autosize" directive to resize my textbox based on the input. i want to have a fixed width for my input field. 
Kindly solve this issue

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
