### ISSUE TITLE
the demo site not working 

### ISSUE THREAD

**Issue by zamboney** [mbenford/ngTagsInput#582]
Plunker isn't showing <a href="http://mbenford.github.io/ngTagsInput/demos">demos</a>

**Comment by mbenford** [comment]
It seemed to be some issue on Plunker's side. Anyway, everything is working again.

**Comment by alexweber** [comment]
@mbenford Seems to be unavailable again at the moment....

**Comment by Tav0** [comment]
This is still unavailable.

**Comment by mrbormeth** [comment]
The demo-site it not working because of this :) 

Mixed Content: The page at 'https://mbenford.github.io/ngTagsInput/demos' was loaded over HTTPS, but requested an insecure script '***'. This request has been blocked; the content must be served over HTTPS.

Here are some of the demos:
http://embed.plnkr.co/RHm7H2/preview Simple tags input
http://embed.plnkr.co/bDx54d/preview Simple tags input with autocomplete
http://embed.plnkr.co/o53tZd/preview Tags input with custom objects

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
