### ISSUE TITLE
Browser centers when  <tags-input> is on the page

### ISSUE THREAD

**Issue by landerarnoys** [mbenford/ngTagsInput#586]
Hello,

I have the ngTagsInput directive on my page, along with some text fields. When i update one of these text fields the browser centers itself, which should not happen. If i remove the <tags-input> from the HTML, this strange behaviour not happen.

Is this a known issue?

The HTML:
  <tags-input  ng-model="exp.tags" ng-if="vm.editable"
                                    replace-spaces-with-dashes='false'
                                    add-on-comma="false"
                                    class="ko-tag"
                                    on-tag-clicked="vm.tagClicked($tag, exp)"
                                    min-length="1"

```
                                vt-tag-input-changed
                                onafterblur="vm.updateResume()"
                    >
                        <!--on-tag-added="vm.updateResume()"-->

                        <auto-complete source="vm.loadTags($query)" min-length="2"
                                       select-first-match="false"></auto-complete>
```

 </tags-input>

Thanks!

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
