### ISSUE TITLE
Autocomplete : search in 2 fields instead of 1

### ISSUE THREAD

**Issue by Seiifer** [mbenford/ngTagsInput#592]
Is there a way to search in 2 fields of the source json instead of one ?

For example : 
Using the demos `Autocomplete with custom template` or `Tags input and autocomplete with custom templates`

Basically, on text input, I would like to be able to match the name like it already does, but also the confederation.

**Comment by Seiifer** [comment]
Ok, so I ended up doing this : http://plnkr.co/edit/aq0kSciNgtPI7qcPH3vV?p=preview

But now, how can I make both fields having the matching text highlighted instead of just the country name ?

**Comment by Seiifer** [comment]
```html
    <script type="text/ng-template" id="my-custom-template">
      <div class="right-panel">
        <span ng-bind-html="$highlight($getDisplayText())"></span>
        <span>{{$highlight(data.confederation)}}</span>
      </div>
    </script>
```
surround the text with `<em>` tag, is there a way to change it so it makes it `<b>` or `<strong>` ?
-> http://plnkr.co/edit/aq0kSciNgtPI7qcPH3vV?p=preview

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
