### ISSUE TITLE
Plain jQuery version?

### ISSUE THREAD

**Issue by vko-online** [mbenford/ngTagsInput#594]
I like the simplicity of this plugin, really would love to use without angular, possible?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
