### ISSUE TITLE
restrict display of items in autosuggestion dropdown

### ISSUE THREAD

**Issue by SangameshPH** [mbenford/ngTagsInput#597]
Can we restrict displaying of number of items in autosuggestion dropdown? And also can we have custom dropdown with extra item?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
