### ISSUE TITLE
autocomplete show message if no search results.

### ISSUE THREAD

**Issue by nithinkrishnanp** [mbenford/ngTagsInput#598]

**Comment by turistua** [comment]
+1

**Comment by shankarregmi** [comment]
+1

**Comment by abojar** [comment]
+1

**Comment by shyamal890** [comment]
+1

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by shyamal890** [comment]
Currently have added a manual item with `ng-if` for this purpose. Would appreciate if this is included in the core plugin
