### ISSUE TITLE
autocomplete issue in ngtagsinput

### ISSUE THREAD

**Issue by dskr133** [mbenford/ngTagsInput#599]
hi mbenford.github.io/ngTagsInput is the ngtagsinput directive we are using in our angularjs app. As ngtagsinput autocomplete does not filter any results, i want to get the filtered results from my api through service call and return promise to the autocomplete of tagsinput on every key stroke. In my angularjs app i am getting the filtered results from the api on every keystroke but they are not appearing in view i.e., the auto complete results displayed are not updating on keystroke even though i am getting the results from api. Can anyone help me in achieving this.

**Comment by mmeloni** [comment]
+1

**Comment by sprakashg** [comment]
+1 Same issue

**Comment by sprakashg** [comment]
Hi Team,
I solved this issue, by setting a $timeout function for the api response, and debounce-delay.

**Comment by dskr133** [comment]
https://github.com/sprakashg can you let me know what are the values used for debounce-delay and $timeout

**Comment by dskr133** [comment]
Hi @sprakashg can you explain briefly how you have solved the issue

**Comment by sprakashg** [comment]
I set the  debounce-delay="some number(300)" for <auto-complete>

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
