### ISSUE TITLE
Readonly mode

### ISSUE THREAD

**Issue by nvurgaft** [mbenford/ngTagsInput#601]
Question, does ngTagsInput support/has readonly mode ?

What I'm looking for is having it disabled for human input, I just want my controller to insert items to the tags-input on some user events, but I do want the user to be able to remove them (x to close)

![ngtagsreadonly](https://cloud.githubusercontent.com/assets/1694752/12094976/77f91d5e-b314-11e5-8bc4-d0b7934aaa5b.png)

I tried using html to disable the input but that didn't work, just changed the style.

My question on SO
http://stackoverflow.com/questions/34509624/ng-tags-input-how-to-disable-user-input

**Comment by mertenhanisch** [comment]
Duplicate: #241 
It is not explicitly stated in the documentation, but you can do `<tags-input disabled="true"></tags-input>` which will work.

**Comment by nvurgaft** [comment]
That just disabled the entire input, I still need to remove the tags by clicking their "x"

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by vdevappa** [comment]
I want to make this dynamic based on a flag. What I see with the version I have is whether I use disabled="true" or disabled="false", it remains disabled.

**Comment by mmnaseri** [comment]
@vdevappa you can use `ng-disabled="..."` which adds the `disabled` HTML attribute conditionally.
