### ISSUE TITLE
Autocomplete with custom promises Highlight vs Used

### ISSUE THREAD

**Issue by tothsanka** [mbenford/ngTagsInput#604]
I tried Autocomplete with custom promises on your demo page. I chosen "Autocomplete with custom promises" mode and typed Tag9. The Tag9 was highlighted properly in the selection, BUT in case of [ENTER] the first option was used from the selection, not the highlighted one. I just wondering if it is an easy fix.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
