### ISSUE TITLE
Changing tags class style on focus

### ISSUE THREAD

**Issue by bgold0** [mbenford/ngTagsInput#605]
I am trying to have the border change on this element when the user is focused on the input box typing in tags.

```
<div class="tags" ng-class="{focused: hasFocus}">
```

According to my developer tools, when the input box is focused, it should be `div.tags.focused`. I've done the following but it still does not change the style. Any tips that I am not trying or is something wrong here?

```
div.tags.focused, tags-input .tags.focused  { 
    border:1px solid red;
}
```

**Comment by tatianilima** [comment]
same here

**Comment by zelias500** [comment]
the problem comes from a `-webkit-appearance: textfield;` on the `.tags` class

here's a fix -- implement locally
```
.tags {
    -moz-appearance: initial;
    -webkit-appearance: initial;
}
```
`-webkit-appearance` is being deprecated anyway

**Comment by kevincobain2000** [comment]
@zelias500 ``-webkit-appearance`` doesn't work for me. Any other work around is really appreaciated

**Comment by kevincobain2000** [comment]
```
    .host {
      outline: 0;
    }
```

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
