### ISSUE TITLE
ngTagsInput is blocked by Mobile Safari content blocker "Crystal"

### ISSUE THREAD

**Issue by wkonkel** [mbenford/ngTagsInput#606]
The "Crystal" content blocker for iOS Mobile Safari blocks ngTagsInput because of the string "tags".

Specifically, the CDNJS hosted version is blocked:

```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ng-tags-input/3.0.0/ng-tags-input.min.js"></script>
```

To work around it, download this file and rename it from "ng-tags-input.min.js" to anything without the word "tags" and it is no longer blocked:

```
<script type="text/javascript" src="ng-taZZZgs-input.min.js"></script>
```

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
