### ISSUE TITLE
UI Mask

### ISSUE THREAD

**Issue by itsakap** [mbenford/ngTagsInput#608]
Is it possible to use UI Mask with the new tag input? Would be helpful for validating e.g. phone numbers.

https://github.com/angular-ui/ui-mask

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
