### ISSUE TITLE
ng-keyup or ng-blur doesn't work

### ISSUE THREAD

**Issue by webdev** [mbenford/ngTagsInput#609]
It looks like ngTagsInput takes over `ng-keyup` completely. Is there any way to tap into `ng-keyup` so I can run my own code when event occurs?

**Comment by sarbjeetsingh** [comment]
$(document).on('keyup','.tags input', function(e){
    var key = e.which;
   if(key == 13)  // the enter key code
    {
      alert('hello');
    }
  })

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
