### ISSUE TITLE
Support grouping in autocomplete

### ISSUE THREAD

**Issue by Urigo** [mbenford/ngTagsInput#61]
Hi, is there a way to support group inside the autocomplete?
![screen shot 2014-01-29 at 1 41 34 pm](https://f.cloud.github.com/assets/1297448/2029125/794c54ae-88dd-11e3-93af-a7accf604222.png)

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
