### ISSUE TITLE
Unable to disable auto-select on tab

### ISSUE THREAD

**Issue by jfairley** [mbenford/ngTagsInput#611]
First off, great component. I'm looking to switch to this from ui-select. 

In my app, I'm setting up this component to open the auto-complete immediately on focus. Unfortunately, this makes the feature of adding a suggestion on tab really undesirable.

In particular, I'm thinking of the keyboard junkies who prefer to use the tab key to navigate forms. As is today, tabbing into this input will open it and select the first item. Tabbing out will choose that item. If I wanted to just tab to the next form item without making changes, I cannot.

One option I have today is to disable the feature to select the first match. This, too, is undesirable, as the user would then have to type then _down arrow_ then press enter. Again, keyboard junkies want to just tab in, type something, press enter, and move on.

<br>
- Can this be made into a configurable option?
- What are your thoughts on this change?
- Would this come more quickly if I make a PR? ( I see there are quite a few outstanding PRs already... )  

Thanks

**Comment by MeirKriheli** [comment]
:+1:

**Comment by Seiifer** [comment]
Might be done by editing [this line](https://github.com/mbenford/ngTagsInput/blob/master/src/auto-complete.js#L242) ?

**Comment by jfairley** [comment]
@Seiifer That's exactly the line I'm looking at. For now, I'm just holding off to see how @mbenford makes progress through the existing pile of PRs.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
