### ISSUE TITLE
Disable 'add-on-tab'

### ISSUE THREAD

**Issue by Seiifer** [mbenford/ngTagsInput#614]
Ok so, I know there is no `add-on-tab` but this illustrates what I'm talking about pretty well.

Is there any way to disable the action of the `Tab` key ?.

Currently, pressing `Tab` will add the selected options.

But in most of the cases, when people are pressing `Tab`, they just want to switch to the next form field.

I'm guessing it's [this line](https://github.com/mbenford/ngTagsInput/blob/master/src/auto-complete.js#L242)  but there is maybe more to edit.

Regards.

**Comment by jfairley** [comment]
Same request as mine: https://github.com/mbenford/ngTagsInput/issues/611

**Comment by Kiranrajkathula** [comment]
This will switch to the next section and new tag suggestion will not be added.  

If using ng-tags-input.js  remove KEYS.tab in and make sure it is only 

`else if (key === KEYS.enter) {
                            handled = scope.addSuggestion();
                        }`

remove a.tab from ng-tags-input.min.js  before addSuggestion function and make sure it is like the following 

`(d===a.enter)&&(e=b.addSuggestion())`

Hope this help :)

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
