### ISSUE TITLE
Grunt watch to rebuild or serve compiled files

### ISSUE THREAD

**Issue by sibelius** [mbenford/ngTagsInput#615]
Somebody knows how to modify the grunt watch task to instead of running all the test, it also build and/or serve in a specific address (how I can use a link in my main project, like: localhost:3456/ng-tags-inputs/ng-tags-input.js)?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
