### ISSUE TITLE
How to add a confirmation in on-tag-removing ?

### ISSUE THREAD

**Issue by bagusflyer** [mbenford/ngTagsInput#616]
I'd like to add a prompt when user click the **remove** button. I'm using cgPrompt. But the problem is cgPrompt (and other similar services) are all implemented in promise which is async. 

For example,

```
   function removeTag(tag) {   
        prompt({
           title: 'Confirmation ?',
          message: 'Are you sure you want to delete this tag ?'
       }).then(function(){
      });
   }

```

I don't know where to return **true** or **false**. Any suggestion? Thanks.

**Comment by fracz** [comment]
Duplicate of https://github.com/mbenford/ngTagsInput/issues/569

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
