### ISSUE TITLE
Open auto-complete suggestions as drop-up or pop-up?

### ISSUE THREAD

**Issue by larifari** [mbenford/ngTagsInput#617]
Is there an easy/obvious way to get the auto-completion suggestions to open as drop-up or pop-up instead of the customary dropdown? This would be useful for touch interfaces as the following form fields would not be obscured from view/click.

**Comment by shyamal890** [comment]
+1

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by shyamal890** [comment]
This would be a great addition to ngTagsInput. Please do consider reopening this issue
