### ISSUE TITLE
on-tag-adding not working with duplicate value

### ISSUE THREAD

**Issue by jitenderchand** [mbenford/ngTagsInput#618]
I am facing a problem with ngTagInput. When I am entering the same value which already there then Its tag-adding event not working. I do not want restrict user to entering value. But user have to make selection from the list which I provide. So I have bind click function to my span.

<span ng-hide="genre.isSubGenresVisible" class="tag-comedy" ng-click="selectGenre(genre,event)">

<tags-input on-tag-adding="validate($tag)" text="text" ng-blur="text =''" ng-focus="istrendingList = true" display-property="name" ng-model="beamNowData.tags" placeholder="What is about? (Genre)"></tags-input>

**Comment by mcmahonjohn** [comment]
I am also encountering an issue with duplicate value. I have key-property and display-property set, but I am getting the following error:

Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: tag in tagList.items track by track(tag), Duplicate key: undefined, Duplicate value: Band

@mbenford any suggestions? Otherwsie, if I just try and add a string, I get an error because the string has 2 in it more than one time.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
