### ISSUE TITLE
Allow selection and editing of tokens

### ISSUE THREAD

**Issue by ticky** [mbenford/ngTagsInput#62]
It would be very useful if one could;
- Select tags using the arrow keys or mouse
- (Optionally) Edit existing tags when selected (or clicked)
- Select multiple tags using the arrow keys and Shift, or with the mouse (⌘/Control+Click)

**Comment by maplesap** [comment]
+1! Would love to see this for ngTagsInput.

**Comment by mbenford** [comment]
Tag navigation is implemented in master. Tag editing will come in a future version because it's implementation needs further thinking.

**Comment by SirCaprice** [comment]
Hi @mbenford, 
is this editing feature now implemented? i would need that feature too but i can't find it. 
For example: **i want to edit the first of my ten tags. **
To do this now i would have to delete all the other tags. for my work this would be inefficient.
Thanks 
Alex

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
