### ISSUE TITLE
After removing tag, auto-complete list doesn't open again

### ISSUE THREAD

**Issue by yanasivanexl** [mbenford/ngTagsInput#624]

**Comment by mikekoro** [comment]
I am having this issue as well. So basically you have to click somewhere outside the input tag element and then click it again.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by julesbou** [comment]
Hey, i'm re-opening if you don't mind. I think it's a simple issue to fix, and the problem is still present. Cheers
