### ISSUE TITLE
Why is bower referencing an other repo?

### ISSUE THREAD

**Issue by sikko** [mbenford/ngTagsInput#626]
When installing from bower it actually fetches from this repo: https://github.com/mbenford/ngTagsInput-bower

Which apparently has been updated 7 months ago last time.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
