### ISSUE TITLE
$translate and variable with hundreds of rows

### ISSUE THREAD

**Issue by hmendezm** [mbenford/ngTagsInput#627]
Hi Guys,

I have two questions/issues
1. I am developing a multilingual app so I need the selected values translate according to the user language selection.  is it a way to do this with your directive? 
2. I have a product list with the following format  
language_id: 1,name: "Other horticulture",product_id: 859
This product list is hundreds of rows. I notice that when I enter first chars only show my the 10 first products and not the rest. So If I enter the chars of the last product I was not able to choose from the list. What do I do wrong?

Best Regards
Henry

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
