### ISSUE TITLE
input type doesn't work

### ISSUE THREAD

**Issue by MikaAK** [mbenford/ngTagsInput#632]
From the docs It mentions allowing of the attribute `type` claiming it does: 
`Type of the input element. Only 'text', 'email' and 'url' are supported values.`

However I've given it `type='email'` and it is still allowing me to submit with invalid emails and the element still has `ng-valid`

**Comment by stringbeans** [comment]
+1 ! we're noticing this as well

**Comment by victorbadila** [comment]
+1 I'm getting this as well

**Comment by mepdr** [comment]
we're noticing this as well

**Comment by octavioamu** [comment]
+1 Any solution?

**Comment by StyxOfDynamite** [comment]
As a work around I'm doing aquick regex check of the $tag in `on-tag-adding`

**Comment by StyxOfDynamite** [comment]
As a work around I'm doing a quick regex check of the $tag in `on-tag-adding`

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by StyxOfDynamite** [comment]
I think this issue should probably be reopened if you intend to support the `email` type attribute.
