### ISSUE TITLE
http://shrub.appspot.com/ng-tags-input not working...

### ISSUE THREAD

**Issue by canivel** [mbenford/ngTagsInput#634]
Hi the link for the latest build is not working... where can I get the last build?

tks!

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
