### ISSUE TITLE
Allow duplicates in DropDown.

### ISSUE THREAD

**Issue by akhil10x5** [mbenford/ngTagsInput#636]
Hello, I am current using v3.0.0 and i am not sure how would i display duplicate values in multiselect dropdown after going through the documentation.

**Comment by stefanheimann** [comment]
what do you need duplicates for?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
