### ISSUE TITLE
Sends extra character after deleting all characters if `debounce-delay` nonzero

### ISSUE THREAD

**Issue by eric-aver** [mbenford/ngTagsInput#637]
If I type some characters, then delete all of them, `myFunction` is sent a single character, the first one entered. (if `abc` is entered, then deleted, a call is made with `a`, for example.)

```
          <tags-input
            ng-model="my.model"
            type="text"
            ng-disabled="disableEditing"
            replace-spaces-with-dashes="false">
            <auto-complete source="myFunction($query)"
                           min-length="0"
                           debounce-delay="300"
                           max-results-to-show="10"/>
          </tags-input>
```

ngTagsInput v3.0.0
AngularJS v1.3.20
Chrome 48.0.2564.116 (64-bit) (OS X)

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
