### ISSUE TITLE
Field is being validated automatically when required is set

### ISSUE THREAD

**Issue by diegofalciola** [mbenford/ngTagsInput#641]
When I set the "required" attribute, as soon as the page is loaded the field appears in red. This is not the default behavior of the required attribute right?

Is this something being fixed currently?
Thanks!

**Comment by joaocmfcm** [comment]
I am running to the same issue. The validation should only be done on $dirty or $touched states, I guess

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
