### ISSUE TITLE
Publish (release) bootstrap scss files

### ISSUE THREAD

**Issue by razvanz** [mbenford/ngTagsInput#644]
I think it would be useful to publish the scss files for folks like me who like to customise the style without having to define overwrites for the CSS rules, but rather use scss variables.

**Comment by azachar** [comment]
:+1:

**Comment by davinkevin** [comment]
Will help for my other issue https://github.com/mbenford/ngTagsInput/issues/559

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
