### ISSUE TITLE
on click of close button, it removes the last one in array

### ISSUE THREAD

**Issue by sprakashg** [mbenford/ngTagsInput#645]
Following is the array of objects.
[{"id" : 1, "label" : "men"}, {"id" : 2, "label" : "women"}, {"id" : 3, "label" : "kids"}]
`<tags-input ng-model="tags" placeholder="Link this sale to a tag" display-property="path" replace-spaces-with-dashes="false" add-from-autocomplete-only="true" on-tag-added="tagAdded($tag)" on-tag-removed="tagRemoved($tag)" >
    <auto-complete source="loadTags($query)"></auto-complete>
  </tags-input>`
When I click on x mark above 'men' tag, it removes 'kids' tag from the input

**Comment by DKirwan** [comment]
I can reproduce. Strangely, when I use the minified JS version this defect does not occur.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
