### ISSUE TITLE
Keyboard-shortcuts supporting other keyboard layouts

### ISSUE THREAD

**Issue by d3QUone** [mbenford/ngTagsInput#646]
On click `,` on the keyboard the tag is "submitting". This is OK if you are using the default English layout. But if you switch to other language (e.g. Russian), you have another placement of chars, and submit on hitting comma `,` may be rather annoying (in Russian we have letter `б` on the same place as comma `,`)

Could you add some kind of "language support"? 

ng-tags-input: 3.0.0
angular: 1.4.7
browser: Safari 9.0.3, Chrome 49.0.2623.97

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
