### ISSUE TITLE
on-tag-adding does not work with promises

### ISSUE THREAD

**Issue by geoguide** [mbenford/ngTagsInput#648]
I want to add a tag but before I do I want to check with the server to make sure it's okay I am returning a promise with true or false, but it always evaluates as true and the tag always gets added even on error. I can't figure out how to fix this.

```
var deferred = $q.defer();

someFunction(tag).then(function(result){
deferred.resolve(true);
}, function(error){
deferred.resolve(false);
});
return deferred.promise;
```

`<tags-input on-tag-adding="someFunction($tag)" ... >`

**Comment by fracz** [comment]
Duplicate: https://github.com/mbenford/ngTagsInput/issues/569

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
