### ISSUE TITLE
Autocomplete shows only one result

### ISSUE THREAD

**Issue by manuschiller** [mbenford/ngTagsInput#649]
Hi,

i got the problem, that autocomplete always only displays the first item of my object list.
i set max-results-to-show="10" and double checked, that my array contains more than 1 object.
do you have any hints for me?

**Comment by noherczeg** [comment]
At the time of writing it works fine for us. Is the JSON valid?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
