### ISSUE TITLE
ngTagsInput with autocomplete not working in iOS Safari

### ISSUE THREAD

**Issue by svfat** [mbenford/ngTagsInput#653]
I'm entering text, but dropdown doesn't appear, and entered values aren't valid (though they are). On desktop everything ok. Not sure how to debug it on iPhone. Any advices?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
