### ISSUE TITLE
Multiple autocompletes open when focus changes within debounce delay

### ISSUE THREAD

**Issue by jkjustjoshing** [mbenford/ngTagsInput#654]
If the user blurs the tag input field during the debounce-delay period, the autocomplete doesn't close. This can result in multiple autocomplete windows open at the same time.

Reproduction plunker at http://plnkr.co/edit/z7vbsy6qQDBPSE48R872?p=preview. To reproduce:
    1) Focus the first input
    2) Type "tag", and then within the 2 second debounce delay, focus the second input
    3) Type "tag" in the second input

The expected functionality is that the second autocomplete dropdown will become visible after the 2 second delay, but the 1st one should never appear. Currently (v3.0.0, Angular v1.4), both autocompletes become visible, layering very weirdly.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
