### ISSUE TITLE
Have a variable minTags quantity?

### ISSUE THREAD

**Issue by ncescau** [mbenford/ngTagsInput#656]
Hi !

First of all, sorry for my english.

I'm looking after a way to specify a variable minTags, with a Javascript value defined in my AngularJS Controller.

Practically, depending to a value stored into my database, the min-tags should be 0 or 1. I tried to use those lines, but it doesn't work :

<tags-input ... min-tags="{{ MyData.mandatory }}">
<tags-input ... min-tags="MyData.mandatory">
(where MyData.mandatory is 0 or 1).

Is there a solution for this issue?

Thanks for your help !
Nathan

**Comment by tanhauhau** [comment]
If i am not mistaken, are you trying to do something like this?

```html
<script>
    angular.module('myApp', ['ngTagsInput'])
               .controller('MyCtrl', function($scope) {
                     $scope.minTag = 0; //depends on logic
               }
    }
</script>
<tags-input ng-model="tags"
                   min-tags="{{minTag}}">
</tags-input>
```

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
