### ISSUE TITLE
Suggestion: Change order by drag and drop

### ISSUE THREAD

**Issue by cschwaderer** [mbenford/ngTagsInput#658]
ngTagsInput is a great directive, we use it at various points throughout our application. However, in one use case, it would be nice if the end user could change the order of the tags via drag and drop. I know, for standard tags, order doesn't matter, but in this special case it does.

Maybe including an existing drag and drop library/module that would not be too much work.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
