### ISSUE TITLE
Suggestion: Id on input element

### ISSUE THREAD

**Issue by jcdesousa** [mbenford/ngTagsInput#660]
Hi,

ngTagsInput is a awesome directive, but i would like to add an id to the input element so i can have label with focus atribute maybe you could include that.

<label for:"tags"></label>
<tags-input ...>
</tags-input>

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
