### ISSUE TITLE
Avoid input vertical grown

### ISSUE THREAD

**Issue by jonathanwiesel** [mbenford/ngTagsInput#661]
Is there a way to make the tags use only one row inside the input, so when the tags fill the input it just scrolls inside, like if it was long text inside?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
