### ISSUE TITLE
Searching feedback when autocomplete is async function

### ISSUE THREAD

**Issue by jonathanwiesel** [mbenford/ngTagsInput#663]
Is there any supported way to show like a "Searching..." text while the results are being fetched?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
