### ISSUE TITLE
Latest builds should include .tar.zip to be installable via npm

### ISSUE THREAD

**Issue by facultymatt** [mbenford/ngTagsInput#664]
In an attempt to get around the unreleased fix for #593, I'm using the latest builds in the links in the readme. The problem is NPM wants a zipped tarball file, which is not provided. 

See https://docs.npmjs.com/cli/install#description

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
