### ISSUE TITLE
displayProperty should allow the item itself as default

### ISSUE THREAD

**Issue by nescalante** [mbenford/ngTagsInput#666]
Hi, nice library, we have been using it for a while in our company.

we have the following use case:

``` js
$scope.theModel = ['foo', 'bar', 'baz'];
```

``` html
<tags-input ng-model="theModel"></tags-input>
```

the lib here is changing `theModel` to:

``` js
[{text:'foo'}, {text:'bar'}, {text: 'baz'}]
```

is there a way to prevent that model change?
can we keep the model format as is? (I mean, as an array of strings)
do we have a workaround to solve that issue?

Thanks in advance.

**Comment by SargoDarya** [comment]
We kind of have the same problem at the moment although your output is wrong. 

For the following input

    ['foo', 'bar', 'baz]

It returns:

    [{text:'foo'}, { text:'bar'}, { text: 'baz'}]

**Comment by sebastiannm** [comment]
https://github.com/mbenford/ngTagsInput/pull/679 this will fix it.. Just waiting for the response

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
