### ISSUE TITLE
How to watch newTag.invalid in ngTagsInput?

### ISSUE THREAD

**Issue by nhoctanker** [mbenford/ngTagsInput#671]
I'm using ngTagsInput to implement recipient list. To show inline validation message I add "on-invalid-tag" property. The question is that I need to hide the message after users see the message and start to correct there wrong input by deleting or adding something.

In default style, if the new input is invalid, it's printed in red when users try to create the new tag. But then if they press backspace or any input any letter, the color turns to normal. That behavior is just what I want for my validation message, it should absolutely appear and disappear together with the red text binding with newTag.invalid in ng-tags-input.js.

But there seems to be no such event or function. And I tried to use ng-change to catch the change event of input, but it doesn't work. Is there a way to do so?

Here's the code.

<tags-input ng-model="recps" 
        display-property="recipient"
        replace-spaces-with-dashes="false" 
        on-tag-removing="removeRecipient($tag)"
        allowed-tags-pattern="^[A-Za-z0-9]+([-_.][A-Za-z0-9]+)*@[A-Za-z0-9]+([-_.][A-Za-z0-9]+)*.[A-Za-z]{2,5}$"
        on-invalid-tag="invalidTagInput($tag)"
        ng-focus="validData.validRecipients=true;">
</tags-input>

<div class="email-address box" ng-show="!validData.validRecipients">
    {{validationMsg}}
</div>

//js code here
$scope.invalidTagInput = function(tag) {
    $scope.validData.validRecipients = false;
};

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
