### ISSUE TITLE
Autocomplete with $resource

### ISSUE THREAD

**Issue by hmendezm** [mbenford/ngTagsInput#672]
Autocomplete is working as expect but I have I littler problem. I would like that when the user selected an item, the autocomplete does not show the list again until the user enters other text. Users have to click outside the control to be able to continue with the other controls in the form

is it a way that I can avoid this and just show the list when user click again or enter a nes text in the control?

Thank you very mush for this work.
Henry

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
