### ISSUE TITLE
Doesn't work on iPhone with scroll

### ISSUE THREAD

**Issue by ravindueranga** [mbenford/ngTagsInput#673]
The button doesn't stay on the bottom of the page in iPhone when scrolling. Sometimes button disappear at all. Same in any browser on iPhone

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
