### ISSUE TITLE
bug with adding a tag

### ISSUE THREAD

**Issue by bkinsey808** [mbenford/ngTagsInput#675]
the SECOND time you click tab to add a new tag, the tag does not get added, and the tags input enters some kind of error state.

To reproduce, go to:

http://mbenford.github.io/ngTagsInput/demos

Click on "Tags input and autocomplete with custom templates"

Enter a new tag (not one that already exists and hit tab. Tag is successfully added. Great.
Now enter another new tag. Hit tab. Tag is not added, input turns red.

**Comment by noherczeg** [comment]
We use 3.0.0 since newer version did not work at all. This bug is present in this version as well!

**Comment by rickbeddard** [comment]
I ran into this and had to remove the key-property attribute.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
