### ISSUE TITLE
tab to add tag

### ISSUE THREAD

**Issue by bkinsey808** [mbenford/ngTagsInput#676]
When tab can add a new tag, i recommend that there is an option to disable tab navigation to the next tabbable element.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
