### ISSUE TITLE
UI does not update with ngModel is updated

### ISSUE THREAD

**Issue by aaaku** [mbenford/ngTagsInput#677]
For some reason, my tags input UI does not seem to update when I update my backing model. This is not an issue with $apply. Other elements in the same form are getting updated. 

I am clearing the model array (with the {text: whatever} objects) and loading the array with new objects. If it matters, I am using this with ionic. My usage code is simple:

&lt;tags-input ng-model="searchParamsUi.searchTagsObj" placeholder="...">
  &lt;auto-complete source="loadTags($query)">&lt;/auto-complete>
&lt;/tags-input>

Everything else works great. Thanks. 

I tried looking inside the code and it was not obvious what was supposed to trigger on model change. I dont see a watch on the model. If this is _not_ a known issue, could someone suggest where I should start debugging this (inside ng-tags-input.js) ?

**Comment by lewp** [comment]
Also interested in a solution for this.

**Comment by Olu93** [comment]
I am also interested in this.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
