### ISSUE TITLE
Option to take simple arrays

### ISSUE THREAD

**Issue by kotpal** [mbenford/ngTagsInput#678]
ngTagsInput is great but has one major deficiency, or rather, requires one major improvement. Which is to take a simple array instead of requiring the array (or worse, changing the array) to be an array of objects. 

https://github.com/monterail/angular-tagger for example takes a simple array instead of requiring an object array.

**Comment by mohag519** [comment]
+1

@sebastiannm How do you make this change? I'd like to do it aswell.

**Comment by sebastiannm** [comment]
@mohag519 I will provide a PR today. I just remove all the [display/value] stuff

**Comment by sebastiannm** [comment]
https://github.com/mbenford/ngTagsInput/pull/679

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
