### ISSUE TITLE
BUG: Tag Text overflow issue

### ISSUE THREAD

**Issue by shyamal890** [mbenford/ngTagsInput#681]
Check out the plunker. Incase the tag text is very long, it should be trimmed to appropriate length with ellipsis.

Example: http://plnkr.co/edit/ezaIerWsZMKZ6Lpxdat4?p=preview

I am using this as a workaround for now:

```
<div class="tag-template">
    <div>
        <span ng-show="$getDisplayText().length <=20">{{$getDisplayText()}}</span>
        <span ng-show="$getDisplayText().length >20">{{$getDisplayText() | limitTo: 20}}..</span>
        <a class="remove-button" ng-click="$removeTag()">×</a>
    </div>
</div>
```

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by shyamal890** [comment]
This bug is still there.

**Comment by nadavsn** [comment]
This issue still exists.
I managed to half-fix it using:

```
tags-input .tags .tag-item {
  [...]
  white-space: nowrap;
  text-overflow: ellipsis;
  max-width: 99.9%;
}
```
and adding `float: right` to `.remove-button`

However, this is a 'half-fix' because the X button is really hard to click on because of the text overflow.
