### ISSUE TITLE
Any way to load autocomplete options onclick?

### ISSUE THREAD

**Issue by lzoumas** [mbenford/ngTagsInput#684]
Hello,

Was wondering if there was a way to open autocomplete options when the tag input textbox is clicked, then close them when a selection is made? Right now I am using loadOnFocus and that works when clicked, however when a selection is made, the autocomplete options stay open. I would like it to close when a selection is made.

I am basically trying to replicate the metrics and dimensions behavior in the GA Query Explorer...

https://ga-dev-tools.appspot.com/query-explorer/

Thanks!

**Comment by jmayday** [comment]
Together with my team mate we've solved this problem last days and because it was a little bit tricky I'll try to share our work. 

- we wanted custom icon instead of placeholder text 
- we wanted it to react on click

Remove placeholder text (angular app configuration):
```
tagsInputConfigProvider.setDefaults('tagsInput', { placeholder: '' });
```

Add custom icon instead of placeholder (we use SCSS):
```
tags-input {

	.tags {

		.input {
			padding-left: 0px !important;
			width: 0px !important;
		}

		> span {

			display: block !important;
			visibility: visible !important;
			width: 1px;

			&::after {
				content: '\f055';
				cursor: pointer;
				font-family: FontAwesome;
				font-size: 24px;
			}
		}
	}
}
```

Configure auto-complete to react on arrow down key:
```
<auto-complete
	min-length="0"
	source="categories"
	load-on-down-arrow="true">
</auto-complete>
```

Trigger arrow-down when custom icon is clicked:
```
scope.open = function (event) {
	if (!angular.element(event.target).is('span.input')) {
		return;
	}

	$timeout(function () {
		element.find('input').trigger(new jQuery.Event('keydown', {keyCode: 40}));
	});

};
```

You have of course bind it first on ng-click of your tags-input: 
```
ng-click="open($event)"
```

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
