### ISSUE TITLE
How can I restrict user not to add new tags which are not in predefined list ?

### ISSUE THREAD

**Issue by vamsikrishnachadalavada** [mbenford/ngTagsInput#685]
Hi @mbenford ,

When i type something which is not available in autocomplete the enter is getting applied.

First i tried the add-from-autocomplete-only attribute.
Secondly along with add-from-autocomplete-only i added  add-on-enter attribute.

Still no luck.
Please let me know is there any alternative or fix for this.

Thanks,
Vamsi

**Comment by vamsikrishnachadalavada** [comment]
Do i have any updates on this ticket

**Comment by tianweiliu** [comment]
@vamsikrishnachadalavada please post your code here for people to look at. I have no problem using the add-from-autocomplete-only attribute as in my project users can not put in anything except the pre-defined list of tags.

**Comment by tianweiliu** [comment]
`<tags-input ng-model="newItem.categories" placeholder="categories" replace-spaces-with-dashes="false" add-from-autocomplete-only="true">`

**Comment by noherczeg** [comment]
I used  `add-from-autocomplete-only="true"` as well, it works.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
