### ISSUE TITLE
transfer of repo ownership

### ISSUE THREAD

**Issue by jpmckearin** [mbenford/ngTagsInput#686]
@mbenford you've done an excellent job, but it seems that you may not have the time to commit to the project. Would you consider transferring ownership, or at the very least giving other's write access to the repo?

Thanks

**Comment by mbenford** [comment]
Thanks for the kind words. I guess I'm not ready to transfer ownership of this project yet, but I absolutely welcome any help in maintaining it. Are you willing to help? If you are, please ping me at @mbenford on Twitter.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
