### ISSUE TITLE
Propagate touch-drag for scrolling on mobile

### ISSUE THREAD

**Issue by dolthead** [mbenford/ngTagsInput#687]
Can you create a property to let us allow touch-drag event propagation from ngTagsInput up the chain?  I want my user to be able to touch and drag up and down to scroll on mobile/touch devices.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
