### ISSUE TITLE
Changing a tags key-property causes glitch.

### ISSUE THREAD

**Issue by BobGamble** [mbenford/ngTagsInput#688]
I have on-tag-added and on-tag-removed functions that update the database as tags are added removed.

In the on-tag-added function I have something like :

$http('/addtag/', tag).then(function(response){
  tag.id = response.data.id;
});

So that when removing a tag I can pass the correct ID to the backend.

This causes a weird display issue where the newest tag added displays the wrong value.

Example. 

I add "tag1".  It displays "[tag1]".
I add "tag2".  Now it shows "[tag1], [tag1]".
I add "tag3".  Now it shows "[tag1], [tag2], [tag1]".
I add "tag4".  Now it shows "[tag1], [tag2], [tag3], [tag1]".

..and so on.  

Any ideas?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
