### ISSUE TITLE
addFromAutocompleteOnly = false and submit form on enter

### ISSUE THREAD

**Issue by jonathanwiesel** [mbenford/ngTagsInput#689]
Having a common HTML form, if you have inside an `tag-input` with `add-from-autocomplete-only="false"`, when pressing enter with no tags to add, the form submit is not called.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
