### ISSUE TITLE
ngModelController not detecting changes properly

### ISSUE THREAD

**Issue by razyalov** [mbenford/ngTagsInput#691]
I'm trying to use the ng tags-input with the angular-input-modified plugin, but for some reason the changes to the tags model are not detected and I can't tell if the issue is on your side or the other module's side so I created a plunker that reproduce the problem in hope that you can confirm that the issue is either with tags-input or not.

https://plnkr.co/edit/bVbKfmE3hRID7Loq4E8N

There are instructions on how to reproduce the issue in the page itself.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
