### ISSUE TITLE
ngTagsInput as an attribute inside HTML <input> element

### ISSUE THREAD

**Issue by utkarsh2k2** [mbenford/ngTagsInput#694]
I have been able to customize ngTagsInput so that instead of an element ie. `<tags-input>`, I get a new directive `tagsInputAttr` which I can use as an attribute inside the standard HTML `<input>` element like  `<input tags-input-attr'>`.  Everything works fine except for the `<auto-complete>` part.
Any suggestions?

Here's my question in detail on stackoverflow : http://stackoverflow.com/questions/38371035/customizing-ngtagsinput-autocomplete-directives-angularjs

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
