### ISSUE TITLE
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed.

### ISSUE THREAD

**Issue by SergeC** [mbenford/ngTagsInput#704]
Have an error when not unique tags in autocomplete or tag input.
Full log:

```
      Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: tag in tagList.items track by track(tag), Duplicate key: Tag1 , Duplicate value: {"text":"Tag1 "}
      http://errors.angularjs.org/1.5.2/ngRepeat/dupes?p0=tag%20in%20tagList.items%20track%20by%20track(tag)&p1=Tag1%20&p2=%7B%22text%22%3A%22Tag1%20%22%7D in /home/user/Downloads/ngTagsInput-master/test/lib/angular.js (line 28667)
      ngRepeatAction@/home/user/Downloads/ngTagsInput-master/test/lib/angular.js:28667:48
      $watchCollectionAction@/home/user/Downloads/ngTagsInput-master/test/lib/angular.js:16604:21
      $digest@/home/user/Downloads/ngTagsInput-master/test/lib/angular.js:16739:25
      compile@/home/user/Downloads/ngTagsInput-master/test/tags-input.spec.js:27:23
```

Simple test to reproduce. Add code below to the file test/tags-input.spec.js:

```
it('triggers angular crash on non unique tags', function() {
            // Arrange
            $scope.tags = [
                { text: 'Tag1'},
                { text: 'Tag1'}
            ];

            // Act
            compile();

            // Assert
            expect(getTags().length).toBe(2);
            expect(getTagText(0)).toBe('Tag1');
            expect(getTagText(1)).toBe('Tag1');
        });
```

**Comment by planty** [comment]
Also seeing the same issue after updating my project to use angular 1.5.8 and ng-tags-input 3.1.1.

The project was previously using angular 1.2.28 and and ng-tags-input 2.3.0 without any errors.

**Comment by mistris** [comment]
In HTML I have
`<tags-input ng-model="..." key-property="id" display-property="text" on-tag-added="onTagAdded($tag)"></tags-input>`

In Angular controller I have function `onTagAdded()` which adds `id` to each tag.
And I get error:
`[ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: tag in tagList.items track by track(tag)`.

If I change `ng-tags-input.js` file by following http://www.tech.shinynewthings.com/?p=115 then everything works without errors but it needs to be fixed in your part (in `ng-tags-input.js`).

**Comment by mistris** [comment]
To fix it without modifying vendors you can just edit your HTML like this:
`<tags-input track-by-expr="$index" ...></tags-input>`

**Comment by khajaamin** [comment]
what happen with this issue ?  
 anybody solved ?  if yes then how ?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by r3wt** [comment]
^ what a bitch move by the repo maintainer.

**Comment by r3wt** [comment]
this issue should be reopened because its an important one. 

My data model looks something like:

{ 
firstname: String,
lastname: String,
id: Integer,
share_percentage: double,
attribution_text: Boolean,
attribution_rd: Boolean,
attribution_images: Boolean,
attribution_other: Boolean
}

So the user uses the tags input with the autocomplete to select the users. then the same array is in a table of inputs so that the user can edit the share_percentage field and the attribution fields which are all booleans. I would really appreciate this to be reopened.
