### ISSUE TITLE
Not working with dvorak layout

### ISSUE THREAD

**Issue by notiv-nt** [mbenford/ngTagsInput#705]
Hello,

On the Dvorak layout, the comma is on the letter W, in that I can not type this letter.
- ng-tags-input 3.1.1
- angular 1.4.8
- Chrome 52, IE(10-11), Edge
- FF (comma not working at all)

![dvorak_keyboard](https://cloud.githubusercontent.com/assets/10743009/17133404/8989ec6e-532e-11e6-9d84-3bba4e8f4010.jpg)

---

In Russian:

На расладке дворака невозможно ввести букву W, так как на qwerty она находится на запятой, баг во всех браузерах (не првоерял оперу), кроме FF, на нем просто пропускает запятую

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
