### ISSUE TITLE
Same directive on multiple <tags-input> applies only to last one

### ISSUE THREAD

**Issue by moisoiu** [mbenford/ngTagsInput#707]
Hello, 

I've made a directive so I can clear invalid tags but for some unknown reason the directive applies only to the last <tags-input>. I've tried with isolate scope but didn't manage to do it, and I don't think is the right way.

I know I've could have tried to change in ng-tags-input.js to clear when is invalid but I want to keep the code clean in case I will update the package.

In the example we have 3 <tags-input> the second one accepts only test and the third one only e-mail, both of them have the **clear-invalid-tag** but it works only on last one.

Plunker:
http://plnkr.co/edit/9XuBs6vxCi6fcqM1IkXl?p=preview

So is there a way I could try to clear invalid tag when user loses focus ? Or could there be added a version like **allowLeftoverText** but the only thing different is that if is invalid and loses focus to clear it out?

**Comment by moisoiu** [comment]
Anyone any tips?

**Comment by moisoiu** [comment]
Some news on this weird issue ?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
