### ISSUE TITLE
get only id's property instead of  full object.

### ISSUE THREAD

**Issue by umair-khanzada** [mbenford/ngTagsInput#708]
Hi,
i want to show label and set id's in model same as select box.
`obj.id as obj.label for obj in array`
any attribute available for this kind of work ?

**Comment by felippenardi** [comment]
@mbenford Michael, does ngInputTags have this feature implemented?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
