### ISSUE TITLE
Documentation is not accurate regarding the tagsInputConfig service

### ISSUE THREAD

**Issue by stgogm** [mbenford/ngTagsInput#709]
On the side navigation it states that tagsInputConfig is a service but the title states `tagsInputConfig (directive in module ngTagsInput)` when it should be `tagsInputConfig (service in module ngTagsInput)`.

The `setDefaults` method is not present on the service and it must be called as a provider using `tagsInputConfigProvider`.

Both statements are misleading.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
