### ISSUE TITLE
Need an id on tags-input to set the focus

### ISSUE THREAD

**Issue by ewahner** [mbenford/ngTagsInput#710]
If I need to set the focus to a specific tags-input control, I cannot do that as the tags are not rendered with an id.  Can we add another attribute to the control that would allow the user to pass in an id to be used?

like:

`<tags-input ng-model="vm.myModel" placeholder="Type something" target-id="this_is_my_id"></tags-input>`

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
