### ISSUE TITLE
Support CommonJS

### ISSUE THREAD

**Issue by sibelius** [mbenford/ngTagsInput#711]
For better compatibility with webpack and browserify

Ref: http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by stevenvachon** [comment]
This should not have been spring-cleaned.
