### ISSUE TITLE
collection-repeat tried to compute the height of repeated elements

### ISSUE THREAD

**Issue by shivenigma** [mbenford/ngTagsInput#719]
collection-repeat tried to compute the height of repeated elements  "item in allContacts | searchContacts: searchCon", but was unable to. Please provide the "item-height" attribute.

I am using this with ionic, and getting the below error every time the suggestion list appears, and it is not selecting the suggested element when I touch it I am not sure if it is caused by the above error. Tested with android Lollipop.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
