### ISSUE TITLE
Multiple directives [autoComplete, autoComplete] asking for new/isolated scope on

### ISSUE THREAD

**Issue by sibelius** [mbenford/ngTagsInput#721]
![image](https://cloud.githubusercontent.com/assets/2005841/17904103/5ea1739c-6944-11e6-87f3-26b697c78c7c.png)

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
