### ISSUE TITLE
Request to create a on-valid-tag property

### ISSUE THREAD

**Issue by mcmahonjohn** [mbenford/ngTagsInput#722]
Currently there is a property to evaluate expressions when a tag is invalid. But when the tag becomes valid, then there is not a property to complement that situation.

I recognize that the ngTagsInput controller will resolve when a tag changes from invalid to valid. But I believe the end user could use such a property,

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by mcmahonjohn** [comment]
I request thus stay open as a feature request. It would save time on boilerplate code to address the issue when ngTagsInput's own logic could handle it.
