### ISSUE TITLE
Fill in input from controller

### ISSUE THREAD

**Issue by hugsbrugs** [mbenford/ngTagsInput#724]
Hi there, I have two search fields on my page:
- one for a free search
- one for search in tags

I would like to auto fill tag search while typing in the free searh input. So I tried to find scope variable to assign correspondant value. it seems to be newTag.text (ng-model attached to input) but it also seem to be not accessible from the scope. Probably due to directive. Is there a way to fill in search tag input programmatically ?

Thanks for your suggestions !

Hugo

**Comment by lewp** [comment]
I am not exactly sure what you are wanting to do.  Are you trying to do a typeahead search or something else?

**Comment by hugsbrugs** [comment]
I want to fill in tags input search programmatically so that when a user fills free search, it also fills tags search ...

**Comment by lewp** [comment]
Okay,  I believe what you are doing should work as long as both of your inputs are within the same controller.  You may need to do a $scope.$apply() as well depending on how you are doing it.  Otherwise I don't think the scope would get updated until you click the tag input.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
