### ISSUE TITLE
Please provide the "item-height" attribute.

### ISSUE THREAD

**Issue by shivenigma** [mbenford/ngTagsInput#727]
ionic.bundle.js:25510 Error: collection-repeat tried to compute the height of repeated elements "item in allContacts | searchContacts: searchCon", but was unable to. Please provide the "item-height" attribute.

Can anyone tell me what is the issue here?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
