### ISSUE TITLE
IE 11 crashes on typing hyphen in ng-tags-input

### ISSUE THREAD

**Issue by SangameshPH** [mbenford/ngTagsInput#728]
Hi Ben,
I am facing a strange issue, when I type something in ng-tags-input text box with hyphen for example : win8.0-test, IE 11 crashes. 
I see that it is because when you set textContent of element with "-", then it crashes.
Could you please suggest me a solution or workaround? Its very important for me.

P.S. I am allowing user specified text also  in ng-tags.

Thanks,
-/Sammi

**Comment by SangameshPH** [comment]
An update.
This issue is related to textContent not been supported by IE. So this crashes/ freezes IE 11 in Win 7.
But if we use innerText then it is fine. Problem is when to change? ng-tags-input doesnt have event to subscribe for it.

Any help would be appreciable.

Thanks,
Sammi

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
