### ISSUE TITLE
Paste is not handled in autocomplete (AddOnPaste)

### ISSUE THREAD

**Issue by nziswiler** [mbenford/ngTagsInput#730]
When you paste some text in the tagInput it creates a new tag without checking if the tag already exists. So if we insert a tag that already exists, it creates a new tag instead of taking the existing one from the autocomplete.

As result we have two tags with the same name but different objects.

Steps to reproduce:
1. Go on http://mbenford.github.io/ngTagsInput/demos
2. Click on "Tags input and autocomplete with custom templates"
3. Set add-on-paste="true"
4. Insert Switzerland,Algeria,Belgium (Just random countries from the countries.json)

The three pasted items are new created Objects and not the Objects from the countries.json although they exist in this file.

For comparison, if you only insert Switzerland and press enter it takes the Object from the autocomplete. Thats the way how it should work for pasting stuff.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
