### ISSUE TITLE
Javascript injection to autocomplete dropdown items

### ISSUE THREAD

**Issue by JamesAtPropertyMe** [mbenford/ngTagsInput#731]
It looks like if the source of autocomplete contains Javascript code, it will be executed. It could be a vulnerability to hackers. The problem is related to "tiAutocompleteMatch" in ng-tags-input.js, in which scope.$highlight() has line "return $sce.trustAsHtml(text)". It allows script to be executed. If I replace the line with simple "return text", Angular's $sanitize will by-default filter scripts. Alternatively, if I use "tiUtil.encodeHTML(text)", it will encode any HTML, which behaves the same like the text is highlighted and is more preferred.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
