### ISSUE TITLE
getting this issue Failed to parse SourceMap: http://localhost/bower_components/ng-tags-input/ng-tags-input.css.map

### ISSUE THREAD

**Issue by vvanipenta** [mbenford/ngTagsInput#732]
In Css file ng-tags-input.css we have this code at bottom of page

/*# sourceMappingURL=ng-tags-input.css.map */

Which is intentionally commented but multi line comment does not work in .css file so line is executing and throwing error 

Failed to parse SourceMap: http://localhost/bower_components/ng-tags-input/ng-tags-input.css.map

Please remove that code if not required.

Thanks in advance

**Comment by Weestdudochnicht** [comment]
Guys That Task need 10 sec of your Time so please remove that line of Code asap

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by Weestdudochnicht** [comment]
"name": "ng-tags-input",
  "license": "MIT",
  "version": "3.2.0",

already not fixed! 

Please remove the lin 160 in ng-tags-input.css


/*# sourceMappingURL=ng-tags-input.css.map */

**Comment by mebibou** [comment]
@mbenford how come this is not fixed? this makes my webpack config fail. Please either remove the line or add the sourcemap in the `build` folder, this is a critical bug!
