### ISSUE TITLE
Bootstrap-ui styles

### ISSUE THREAD

**Issue by paulcolucci** [mbenford/ngTagsInput#734]
It would be awesome if there was a style sheet for bootstrap-ui

**Comment by skidvd** [comment]
check out [http://mbenford.github.io/ngTagsInput/documentation/guides/bootstrap](url)

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
