### ISSUE TITLE
Disable focus on first match from autocomplete

### ISSUE THREAD

**Issue by BenevidesLecontes** [mbenford/ngTagsInput#735]
Hi! Thanks for this amazing library. I was searching through all the docs, but i can't find any options to disable focus on first match from dropdown. Is there such functionality? 
Sorry for opening new issue.

**Comment by kevincobain2000** [comment]
``elect-first-match="false"``


```
<auto-complete source="loadTags($query)" select-first-match="false" max_results_to_show="10"></auto-complete>
```

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
