### ISSUE TITLE
Allow reset newTag programmatically

### ISSUE THREAD

**Issue by popod** [mbenford/ngTagsInput#738]
Add method to allow reset the "newTag" input programmatically.

Or

In beforAddTag, add an option to reset the "newTag" input if we return false (tag not added). The current behavior is that the input is set as "invalid tag"

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by popod** [comment]
I think this issue is clear enough and could be reopened ? thanks
