### ISSUE TITLE
iOS doesn't focus input field when clicking on host

### ISSUE THREAD

**Issue by mrshowerman** [mbenford/ngTagsInput#740]
Tapping on the host outside the input field doesn't focus it any more on iOS.
The reason seems to be that iOS requires calls to focus() coming synchronously inside a click event (as discussed [here](http://stackoverflow.com/a/16601288), for instance).
Calling the focus() method from within a $timeout() call starting from version 3.1.0 seems to have broken this behavior.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by mrshowerman** [comment]
IMHO, this issue should still be fixed. Keeping in mind that there is already a possible fix (see pull request), I'd appreciate if you could look into this, @mbenford .
