### ISSUE TITLE
Allow focus to component

### ISSUE THREAD

**Issue by pjlasl** [mbenford/ngTagsInput#744]
This is more of a request than an issue.

I am using your component on a modal and I would like for the component to have focus (meaning the user does not need to click inside to begin typing) when the modal is open.

I tried to use the angular ngFocus but was unable to get it to work.

Thanks!

**Comment by ahmedBassell** [comment]
+1

**Comment by ahmedBassell** [comment]
@pjlasl  ngFocus isn't supposed to help, check this http://stackoverflow.com/a/34924347
but i actually tried to add a custom directive for it but i get an error of multiple directives cause i want to make isolate scope to watch some variable to trigger the focus action

> Error: [$compile:multidir] Multiple directives

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
