### ISSUE TITLE
unable to add a tag twice

### ISSUE THREAD

**Issue by mnibras** [mbenford/ngTagsInput#745]
I cannot add one tag multiple times. If i select one tag, that tag not showing again in the list. Is there a way to add a tag twice?

**Comment by wasitaanggara** [comment]
I have same problem, plis any suggest mbenford? thankyou 👍

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
