### ISSUE TITLE
Allow remove all tags in input field

### ISSUE THREAD

**Issue by popod** [mbenford/ngTagsInput#748]
Add an option to clean the input field by adding a "x" button in the right of the input field ?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by popod** [comment]
I think this issue should be reopened. I simply want to add an option that display a button in the input field to remove all tags in it.

Something like this:
<img width="654" alt="capture d ecran 2017-04-18 a 18 44 15" src="https://cloud.githubusercontent.com/assets/3807312/25142449/2b12e0cc-2467-11e7-8f01-a08d7c04f480.png">

**Comment by gauravdixit007** [comment]
I agree with @popod . Seems like a good idea to put a small cross icon which can clear all the tags added so far.
