### ISSUE TITLE
Permanently show autocomplete

### ISSUE THREAD

**Issue by thany** [mbenford/ngTagsInput#750]
I'd love to have an option to permanently show the autocomplete dropdown.

This will make it easier to style the thing, or to debug styling problems down the line. As it is now, if I understand the component correctly, it can't possibly ever show the autocomplete dropdown when the field is not focused. And the field cannot be focused while I'm fiddling with the inspector. And while the dropdown is invisible, it's actually removed from the DOM, making it effectively impossible to do any kind of debugging on it.

It would be fantastic to have an option for this. Doesn't really matter to me how crude an option this would be. But seeing how browsers can focus only one thing at a time (kinda makes sense 🙂), I think we need *something*, right?

For reference, I'm using the ngTagsInput version 3.1.1 on Angular 1.5.8 on Firefox 49.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by thany** [comment]
Well, the problem's still there... Hard to use the devtools on something that automatically disappears.
