### ISSUE TITLE
How to display the dropdown under the input?

### ISSUE THREAD

**Issue by IonicaBizau** [mbenford/ngTagsInput#751]
How to display the dropdown under the input?

![screenshot from 2016-11-08 15-04-02](https://cloud.githubusercontent.com/assets/2864371/20100153/d9e6e02a-a5c4-11e6-9af8-56e3d250ee29.png)

**Comment by IonicaBizau** [comment]
The default is `width:100%`, but I'd like to have auto width and move the dropdown under the `Add a country` input.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by IonicaBizau** [comment]
> If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why.

@mbenford Well, I just wanted to see how to display the dropdown inline. My issue stands still.

I find this a bad way of "fixing" issues. I understand you want to keep the issue tracker clean, tho.

**Comment by mbenford** [comment]
Thanks for replying back. The behavior you want isn't available in the current version of ngTagsInput. Maybe you can achieve it just by tweaking the stylesheets, but I'm not sure if it's that simple due to the structure of the markup used by the directive. If you happen to implement it someday and want to send a PR, I can review it for you.

> find this a bad way of "fixing" issues. I understand you want to keep the issue tracker clean, tho.

I agree that automatic processes might not be ideal, but I don't have the resources to manually triage all the issues that have pilled up over time. I'm counting on people like yourself to come forward and let me know where the cleanup process made a mistake. :)
