### ISSUE TITLE
AngularJS 2.x

### ISSUE THREAD

**Issue by tfont** [mbenford/ngTagsInput#753]
Not much of a 'real' issue.

However, any plans to release an AngularJS 2.x compatible version?

**Comment by anvesh48** [comment]
+1

**Comment by shyamal890** [comment]
+1

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
