### ISSUE TITLE
Clear invalid tags 

### ISSUE THREAD

**Issue by PratibhaP** [mbenford/ngTagsInput#754]
@mbenford as per you mentioned in issue #414  that clear invalid tags option will be introduced in version3.0.0. 
We have 3.1.1 version now. Can you help me to clear invalid tags? 
Thank you in advance.

**Comment by penguin020** [comment]
See my comment in https://github.com/mbenford/ngTagsInput/issues/315

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
