### ISSUE TITLE
javascript alert for which tag a user has clicked on?

### ISSUE THREAD

**Issue by doomghee** [mbenford/ngTagsInput#755]
I'm trying to write some simple javascript code that tells me which tag a user has clicked on. Is that possible with this library?

**Comment by doomghee** [comment]
I found on-tag-clicked but I don't understand how it's supposed to let me know which tag the user clicked on.

**Comment by doomghee** [comment]
I figured it out.

Here is my js:
$scope.hit = function(tag) {
 console.log("tag",tag.text);
}

and my html:
on-tag-clicked="hit($tag)"

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
