### ISSUE TITLE
Any plugin that is inspired from ngTagsInput and built it angular2 with all the features that this plugin has?

### ISSUE THREAD

**Issue by anrepppp** [mbenford/ngTagsInput#757]
mbenford, as our project is migrating from angular1 to angular2 we are completely rewriting the whole application and came into a feature where it is heavily relied on this ngTagsInput. We are using most of the features in this plugin. And finding trouble to find a similar plugin that supports the features that your plugin supports. Do you know any of them that is similar to this plugin?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
