### ISSUE TITLE
Need to be able to specify html title property for tooltip in addition to display-property

### ISSUE THREAD

**Issue by damianohcm** [mbenford/ngTagsInput#762]
I'm binding to a property that has a truncated value for display-property (i.e. "My very long string trunc... ") and need to be able to bind also a non-truncated property to title so that it will display an html tooltip when use hovers the tag (so they will see the html tooltip show i.e. "My very long string truncated")

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
