### ISSUE TITLE
Performance issues with large number of tags pasted

### ISSUE THREAD

**Issue by dganoff** [mbenford/ngTagsInput#764]
I have come across some significant performance issues when pasting a large number (1900) of items into the ngTagsInput directive. In Chrome, the page gets very sluggish and takes 10-15 seconds to respond to user interaction, but with Firefox, I get an error prompt saying my vendor bundle JS script has stopped/timed out and asks if I want to kill it or continue waiting for it to run. This is obviously taxing on our user experience.

Using [this Chrome extension](https://chrome.google.com/webstore/detail/angular-performance/hejbpbhdhhchmmcgmccpnngfedalkmkm), I can see the number of watchers my app is currently using and it seems like each tag creates 5 watchers, which adds up quickly when the directive is handling over 1000 tags. 

I was able to reduce the watchers to 4 per tag by setting the tag-item template to one-way bind the `$getDisplayText()` [here](https://github.com/mbenford/ngTagsInput/blob/master/templates/tag-item.html#L1), but it wasn't enough of an improvement to fix the above issues.

Has anyone else encountered performance issues like this? Thoughts?

Thanks.

**Comment by fyyyyy** [comment]
Same here

**Comment by dganoff** [comment]
I had to re-write my own component that handles pasted data and just copies it into memory elsewhere. There are just too many watchers necessary for the functionality of ng-tags-input. :(

**Comment by fyyyyy** [comment]
Thanks, thats what i feared.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by Slapshot9** [comment]
I have a similar issue.
For me, the tags will not be pasted, but instead a array is bound.
The problem is not only, that this array can contain >1000 tags, but that I have multiple tag-inputs on one page. Each of this can have > 1000 tags at the same time, leading to a huge amount of watchers and therefore slowing down the browser to be unresponsive for many seconds.

I see, that you may need all those watchers to support all current features.
But commenting this issue, I hope that you find time to dig into this problem and find a solution.
