### ISSUE TITLE
How can ngTagsInput autocomplete only show the matched results?

### ISSUE THREAD

**Issue by bobzhang199102** [mbenford/ngTagsInput#765]
Does anyone know How ngTagsInput autocomplete can only show the matched results?

**Comment by shaifulborhan** [comment]
Try this:

Modify your auto-complete directive so that the source attribute is calling a function:

```
<auto-complete source="filterOptions($query)" load-on-focus="true" load-on-empty="true" min-length="1" max-results-to-show="100"></auto-complete>
```

Then the function itself would be something like this:


```
$scope.filterOptions = function($query) {
   return $scope.locationOptions.filter(function(item) {
      return item.name.toLowerCase().indexOf($query.toLowerCase()) != -1;
   });
}
```

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
