### ISSUE TITLE
Using ngTagsInput tags with text inputs?

### ISSUE THREAD

**Issue by phuwin** [mbenford/ngTagsInput#767]
Hi,

I find ngTagsInput a very useful directive. However I want to use it in combination with normal text. So I can achiveve something like this: (the green-ish block is a tag)
![screen shot 2017-01-03 at 13 40 17](https://cloud.githubusercontent.com/assets/8092739/21606757/3c0662d2-d1ba-11e6-8c47-ad117015275c.png)
I have checked the documentations but haven't found anything...

**Comment by enyosolutions** [comment]
Hi,

Not sure why you want to use a tags input to achieve that. If the styling is your main concern, you can achieve that quickly with css.

For example boostrap has the "label" classes that turns your text into a tag...

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
