### ISSUE TITLE
Input validation on "add-on-space" and "add-on-enter"

### ISSUE THREAD

**Issue by fredbouchard** [mbenford/ngTagsInput#768]
``` Version: 3.1.1 ```
``` Angular: 1.5.8 ```

I've setup the ng-tags-input to add a new tag when ```add-on-space```. When it comes to the validation I was expecting to see the ```$error``` being updated when "space" is pressed, but right now it's only happening when we losing the focus on the input field. Then I figured the ```setElementValidity``` is only done onBlur. See below ⬇️ 

![bug-ng-tag-input](https://cloud.githubusercontent.com/assets/20195237/21817974/11735be0-d734-11e6-925e-fa270525473c.gif)

I tried to fix the issue by adding the ```setElementValidity``` to the onKeyDown event but this was still not working. When looking at the ```setElementValidity``` I figured the ```$setValidity``` on ```leftoverText``` will never return ```false``` as long the ```scope.hasFocus``` is ```true```.

Any idea how we could have the validation working on "add-on-space" and "add-on-enter" without getting rid of the scope.hasFocus?

```javascript
setElementValidity = function() {
    ngModelCtrl.$setValidity('maxTags', tagList.items.length <= options.maxTags);
    ngModelCtrl.$setValidity('minTags', tagList.items.length >= options.minTags);
    ngModelCtrl.$setValidity('leftoverText', scope.hasFocus || options.allowLeftoverText ? true : !scope.newTag.text());
};

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
