### ISSUE TITLE
Source map missing in bower repo

### ISSUE THREAD

**Issue by migaber** [mbenford/ngTagsInput#771]
please don't forget this issue
https://github.com/mbenford/ngTagsInput-bower/issues/10

I notice that you neglect all ngTagsInput-bower repo issues

**Comment by noherczeg** [comment]
It's missing in the npm repo as well!

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
