### ISSUE TITLE
placeholder translate doesn't work

### ISSUE THREAD

**Issue by lu592674374** [mbenford/ngTagsInput#772]
I use this in my angular app, but i need to internationalization my app, so i give the attribute "placeholder" a  value like "{'haha_haha' | translate }", but the ngtagsinput get the haha_haha, and not the 'haha_haha''s value, also when i change the language, the placeholder not change.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by hunty** [comment]
I have same problem. Unfortunately  I can't find any workaround. What I found out:
When I open page for first time - placeholder doesn't render from translate filter. Surfing different pages (making work other controllers) and going back to page with `ng-tags-input` translation renders well. But if I make hard reload (Ctrl + F5) it does'n render again. Some kind of cache? Need extra `$apply`?
I would appreciate if you take a look at this issue.
