### ISSUE TITLE
Open suggestion list only when typing '@' and close when typing space

### ISSUE THREAD

**Issue by Lexus7994** [mbenford/ngTagsInput#774]
I've already all the document but it seem I cannot find any attribute that helps me to open suggestion list only when typing '@' and close when typing space. Cound anyone help me to solve this issue?
Is that neccessary to customize ng-tag-input.js file? :D
Thank alot!!

**Comment by weihanchen** [comment]
You can try [here](https://plnkr.co/edit/vxitMJ?p=preview)
The example use attributes of open-pattern and close-pattern for your feature, you can input some pattern to control with suggestion list.
```
<tags-input ng-model="tags" add-on-enter="true" min-length="0" display-property="text" key-property="id" on-tag-added="onTagAdded($tag)">
    <auto-complete source="loadTags($query)" min-length="0" open-pattern="@$" close-pattern="\s$"></auto-complete>
  </tags-input>
```

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by swethasappati** [comment]
Hi, 
   I have used tags-input in bootstrap popup. When I click on tags-input, autocomplete window(suggestionList is visible) is opening but the problem is I have cancel button in bootstrap popup. when the suggestion list is visible and click on cancel button. The cancel button click event is not working. Instead of closing the bootstrap popup, suggestionList is hiding. Click event is not working. How can I resolve this issue? Can anyone help me please.
