### ISSUE TITLE
Progress bar for autocomplete source loading 

### ISSUE THREAD

**Issue by buga1234** [mbenford/ngTagsInput#776]
Hi. Is there some property to set progress bar while data are loading? Thanks

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
