### ISSUE TITLE
remove .selected from tag on .focus=false

### ISSUE THREAD

**Issue by nail60** [mbenford/ngTagsInput#778]
Currently, if you select a tag using backspace or the arrow keys the tag stays selected even if you move to a new input field. Removing focus should remove .selected from the tag.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
