### ISSUE TITLE
Allow the tag delimiter to be configured explicitly 

### ISSUE THREAD

**Issue by JAndritsch** [mbenford/ngTagsInput#95]
As of right now, tags can only be created on comma, enter, space, or blur. This can be configured via these attributes:

```
[add-on-enter="{boolean}"}
[add-on-space="{boolean}"]
[add-on-comma="{boolean}"]
[add-on-blur="{boolean}"]
```

I think it be useful if there was a configuration for a list of extra tag delimiters that the user could choose. You might also be able to get rid of add-on-space and add-on-comma.

Example:

```
scope.addTagOnCharacters = [",",     ";",    "#",    " "]
add-on-character="addTagOnCharacters"
```

You could even go as far as allowing the user to specify which events should trigger the code to add a tag. 

Example:

```
scope.addTagOnEvents = ["blur",     "click",    "focus",    "hover"]
add-on-events="addTagOnEvents"
```

That would also allow adding tags on custom user events.

Example:

```
scope.addTagOnEvents = ["blur", "myCustomEvent"]
add-on-events="addTagOnEvents"
```

**Comment by AlexanderKozhevin** [comment]
Well, this is quite important feature.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by otothem** [comment]
I'd like this feature to be reopened simply because it would make the directive more flexible and usable. For example, my project requires semicolon as a delimiter. It seems I'm not alone in this situation, judging from other issues.
